#!/bin/sh
# Filename:      /etc/grml/fai/config/scripts/GRML/20-sudo
# Purpose:       configure sudo setup of the live-system
# Authors:       grml-team (grml.org), (c) Michael Prokop <mika@grml.org>
# Bug-Reports:   see http://grml.org/bugs/
# License:       This file is licensed under the GPL v2 or any later version.
# Latest change: Sun Sep 16 23:12:25 CEST 2007 [mika]
################################################################################

set -u
set -e

USERNAME=''
[ -r /etc/grml/grml-live.conf ] && . /etc/grml/grml-live.conf
[ -n "$USERNAME" ] || USERNAME=grml

if [ -r /etc/grml/fai/files/etc/sudoers ] ; then
   cp /etc/grml/fai/files/etc/sudoers $target/etc/sudoers
   chmod 440 $target/etc/sudoers
fi

## END OF FILE #################################################################
# vim:ft=sh expandtab ai tw=80 tabstop=4 shiftwidth=3
