#!/bin/sh
set -u
set -e

USERNAME=''
[ -r /etc/grml/grml-live.conf ] && . /etc/grml/grml-live.conf
[ -n "$USERNAME" ] || USERNAME=grml

# FIXME: use /etc/grml/fai/... as base
cat > $target/etc/sudoers << EOF
# sudoers file.
# This file MUST be edited with the "visudo" command as root.
# See the man page for details on how to write a sudoers file.

# Host alias specification

# User alias specification

# Cmnd alias specification

# User privilege specification
root    ALL=(ALL) ALL

# WARNING: This allows the unprivileged $USERNAME user to start commands as root
# WARNING: This is totally insecure and (almost) makes $USERNAME a second root account.
# WARNING: Never allow external access to the $USERNAME user!!!
$USERNAME    ALL=NOPASSWD: ALL

# allow editing of files with editor:
# $USERNAME ALL=NOPASSWD: sudoedit

# usage examples:
# $USERNAME ALL=NOPASSWD: /sbin/hdparm
# $USERNAME ALL=NOPASSWD: /usr/sbin/hwinfo
# Cmnd_Alias DEBIAN = /usr/bin/apt-get, /usr/bin/dpkg, /usr/bin/auto-apt, /usr/bin/apt-file
# $USERNAME ALL=NOPASSWD: DEBIAN
# chroot       ALL=NOPASSWD: /usr/sbin/chroot, /bin/su - chroot
# chroot       ALL=NOPASSWD: /usr/sbin/chroot, /bin/su - chroot

secvpn  ALL=NOPASSWD: /usr/sbin/secvpn, /usr/sbin/pppd
EOF
