#!/bin/sh
set -u
set -e

USERNAME=''
[ -r /etc/grml/grml-live.conf ] && . /etc/grml/grml-live.conf
[ -n "$USERNAME" ] || USERNAME=grml

chroot "$target" addgroup --gid 1000 $USERNAME
chroot "$target" useradd -d /home/$USERNAME -m -s /bin/zsh -g 1000 $USERNAME

sed -i 's/^root::/root:*:/' "$target"/etc/shadow
sed -i 's/^$USERNAME::/$USERNAME:*:/' "$target"/etc/shadow

chroot "$target" chsh -s /bin/zsh root
chroot "$target" chsh -s /bin/zsh $USERNAME
