#!/bin/sh
# Filename:      /etc/grml/fai/config/scripts/GRML/31-motd
# Purpose:       make sure the motd setup is correct
# Authors:       grml-team (grml.org), (c) Michael Prokop <mika@grml.org>
# Bug-Reports:   see http://grml.org/bugs/
# License:       This file is licensed under the GPL v2 or any later version.
# Latest change: Sun Sep 16 23:00:35 CEST 2007 [mika]
################################################################################

set -u
set -e

$ROOTCMD mv /etc/motd.dpkg-new /var/run/motd

## END OF FILE #################################################################
# vim:ft=sh expandtab ai tw=80 tabstop=4 shiftwidth=3
