#!/bin/sh
# Filename:      /etc/grml/fai/config/scripts/GRML/33-aptsetup
# Purpose:       configure Debian package management of live-system
# Authors:       grml-team (grml.org), (c) Michael Prokop <mika@grml.org>
# Bug-Reports:   see http://grml.org/bugs/
# License:       This file is licensed under the GPL v2 or any later version.
# Latest change: Sun Sep 16 23:10:06 CEST 2007 [mika]
################################################################################

set -u
set -e

rm -f $target/etc/apt/sources.list

$ROOTCMD ln -s /etc/apt/sources.list.grml /etc/apt/sources.list

if [ -r /etc/grml/fai/files/etc/apt/preferences ] ; then
   cp /etc/grml/fai/files/etc/apt/preferences $target/etc/apt/preferences
fi

## END OF FILE #################################################################
# vim:ft=sh expandtab ai tw=80 tabstop=4 shiftwidth=3
