#!/bin/bash
# Filename:      grml2ram
# Purpose:       copy compressed GRML image to RAM
# Authors:       (c) Michael Schierl <schierlm-public@gmx.de>, (c) Michael Prokop <mika@grml.org>
# Bug-Reports:   see http://grml.org/bugs/
# License:       This file is licensed under the GPL v2.
################################################################################

set -e

# shellcheck disable=SC1091
. /etc/grml/lsb-functions
# shellcheck disable=SC1091
. /etc/grml/script-functions

check4root || exit 1
check4progs rsync || exit 2

# shellcheck disable=SC1091
. /etc/grml/grml2ram.conf

if ! [ -d "$LIVECD_PATH" ]; then
  error "Could not find Grml Live medium in ${LIVECD_PATH}"; eend 1
  exit 1
fi

IMAGE="${LIVECD_PATH}/${MEDIA_PATH}/${MEDIA_SQUASHFS_NAME}"
if ! [ -r "$IMAGE" ] ; then
  eerror "Cannot read Grml squashfs file ${IMAGE}."
  eerror "Looks like you did run grml2ram already?" ; eend 1
  exit 1
fi

GRMLSIZE="$(du "$IMAGE" | awk '{print $1}')"
RAM=$(/usr/bin/awk '/MemFree/{print $2}' /proc/meminfo)
LOOPDEV=$(/sbin/losetup -j "${IMAGE}" -n -O NAME)

case "$*" in -f|--force)
  ewarn "Forcing copy process for grml-image (${GRMLSIZE}kB) as requested via force option." ; eend 0
    ;;
  *)
    if [ "${RAM}" -lt "${GRMLSIZE}" ]; then
      eerror "Sorry, not enough free RAM (${RAM}kB) available for copying live system (${GRMLSIZE}kB)." ; eend 1
      exit 1
    fi
    tmpfs_space=$(df --output=avail /tmp | tail -1)
    if [ "${tmpfs_space}" -lt "${GRMLSIZE}" ] ; then
      eerror "Sorry, not enough free space in /tmp (${tmpfs_space}kB) available for copying live system (${GRMLSIZE}kB)." ; eend 1
      exit 1
    fi
    ;;
esac

einfo "Copying $IMAGE to RAM, this might take a while."
rsync -a --progress "$IMAGE" /tmp/GRML
LANGUAGE=C LANG=C LC_ALL=C perl << EOF
open LOOP, '<${LOOPDEV}' or die $!;
open DEST, '</tmp/GRML' or die $!;
ioctl(LOOP, 0x4C06, fileno(DEST)) or die $!;
close LOOP;
close DEST;
EOF

# identify cd-rom:
LIVECD_SOURCE=$(readlink -f /run/initramfs/livedev)
[ -n "$LIVECD_SOURCE" ] || LIVECD_SOURCE='/dev/cdrom'

einfo "Unmounting ${LIVECD_PATH}"
umount "${LIVECD_PATH}"
eend $?
einfo "Now you can eject your grml-cd (e.g. run 'eject $LIVECD_SOURCE')." ; eend 0

## END OF FILE #################################################################
