#!/bin/sh
# Filename:      unblacklist
# Purpose:       blacklist module via module-init-tools
# Authors:       grml-team (grml.org), (c) Michael Prokop <mika@grml.org>
# Bug-Reports:   see http://grml.org/bugs/
# License:       This file is licensed under the GPL v2.
################################################################################

[ -n "$MODPROBEFILE" ] || MODPROBEFILE=/etc/modprobe.d/grml.conf
# shellcheck disable=SC1091
[ -r /etc/grml/lsb-functions ] && . /etc/grml/lsb-functions

if [ -z "$1" ] || [ "$1" = "-h" ] || [ "$1" = "--help" ] ; then
  echo "Usage: unblacklist <module>"
  echo "remove blacklisting of module via $MODPROBEFILE"
  exit 1
fi

if [ "$(id -ru)" != "0" ] ; then
  echo "Error: become root before starting $0" >& 2
  exit 100
fi

[ -f "$MODPROBEFILE" ] || touch "$MODPROBEFILE"

if grep -q "^blacklist $1" "$MODPROBEFILE" ; then
  einfo "Removing module $1 from blacklist $MODPROBEFILE"
  sed -i "s/^blacklist.*$1$/# &/" "$MODPROBEFILE"
  sed -i "s/^alias.*$1 off$/# &/" "$MODPROBEFILE" ; eend $?
else
  eerror "Module $1 not blacklisted in $MODPROBEFILE" ; eend 1
fi

## END OF FILE #################################################################
