.TH GRML-BOOTSPLASH 1 "June 4, 2006"
.SH NAME
grml-bootsplash \- script and configuration framework for the grml system
.SH SYNOPSIS
.B grml-bootsplash "||..."
.SH DESCRIPTION
This manual page documents briefly the
.B grml-bootsplash
command.
.PP
\fBgrml-bootsplash\fP provides a text-based simple bootsplash. It is integrated within
the grml-autoconfig(8) framework. You very probably won't need it otherwise, this manpage just documents
what grml-bootsplash does.
.SH OPTIONS
The program grml-bootsplash does not support any options besides the "||..." sequence.
If you want to specify first status of bootsplash use 'grml-bootsplash "|"'.
To specify the last status of bootsplash use 'grml-bootsplash "||||||||||||"' (that's 12 '"').
The maximum number of supported "|" signs is twelve and will be used automatically if more are specified.
.SH BUGS
If you find a bug please report it. See http://grml.org/bugs/
for details about bug reporting.
.SH AUTHOR
grml-bootsplash was written by Michael Prokop <mika@grml.org> and
Florian Keller <Florian.Keller@zuerich.ch>.
.PP
This manual page was written by Michael Prokop <mika@grml.org>,
for the grml project (but may be used by others).
