.\" Filename:      caps-ctrl.1
.\" Purpose:       man page for caps-ctrl
.\" Authors:       grml-team (grml.org), (c) Michael Prokop <mika@grml.org>
.\" Bug-Reports:   see http://grml.org/bugs/
.\" License:       This file is licensed under the GPL v2.
.\"###############################################################################

.\"###############################################################
.TH caps\-ctrl 1
.SH "NAME"
caps\-ctrl \- switch Caps\-Lock key
.\"#######################################################
.SH "DESCRIPTION"
.B grml\-lang
Switch keyboard settings of key known as "Caps-Lock" between
using Caps-Lock either as control- or shift-key. Notice:
running caps-ctrl on console requires root-permissions,
running it in X window system works as normal user.

.SH "BUGS"
Probably. Please report any bugs you find and report
feedback and suggestions to the Grml team.
See https://grml.org/bugs/ for further information.
Thank you!

.SH "COPYRIGHT"
This man page is copyright \(co 2004-2011 by the Grml team.
Included scripts are under various copyrights, please see
the sources.
.\"###### END OF FILE ##########################################################
.\" vim:tw=60
