# This file was deployed via grml-live's
# ${GRML_FAI_CONFIG}/scripts/GRMLBASE/80-initramfs script, using
# ${GRML_FAI_CONFIG}/files/GRMLBASE/etc/dracut.conf.d/55-grml-live-cmdline.conf
#
# Filename:      /etc/dracut.conf.d/55-grml-live-cmdline.conf
# Purpose:       Set dracut Live boot options
# Authors:       grml-team (grml.org),
#                (c) Chris Hofstaedtler <ch@grml.org>,
# Bug-Reports:   see http://grml.org/bugs/
# License:       This file is licensed under the GPL v2 or any later version.
################################################################################

kernel_cmdline=" rd.shell rd.live.dir=/live/%GRML_NAME%/ rd.live.squashimg=%SQUASHFS_NAME% root=live:CDLABEL=%ISO_VOLID% "
