#!/bin/bash

set -u
set -e

# shellcheck source=/dev/null
. "$GRML_LIVE_CONFIG"

# FAI sets $target, but shellcheck does not know that.
target=${target:?}

mkdir -p "$GRML_FAI_CONFIG"/files/REFORM/etc/apt/sources.list.d/
/usr/lib/apt/apt-helper \
    download-file \
    https://reform.debian.net/reform_trixie.sources \
    "$GRML_FAI_CONFIG"/files/REFORM/etc/apt/sources.list.d/reform_trixie.sources \
    "SHA1:3d453dbf355beebf494ce6f61d2110b98e92fcf5"

# install all apt related files
fcopy -M -i -B -v -r /etc/apt
fcopy -M -i -B -v -r /usr/share/keyrings
