#!/bin/sh
# Filename:      grml-live-remaster
# Purpose:       remaster a grml from the live cd
# Authors:       grml-team (grml.org),
#                (c) Michael Schierl <schierlm@gmx.de>,
#                (c) Michael Prokop <mika@grml.org>,
#                (c) Thorsten Glaser <tg@mirbsd.org>
# Bug-Reports:   see http://grml.org/bugs/
# License:       This file is licensed under the GPL v2 or any later version.
################################################################################
# DISCLAIMER:
# this script currently lacks LOTS of error checking code... any help welcome...
################################################################################

# define function getfilesize before "set -e"
if stat --help >/dev/null 2>&1; then
  getfilesize='stat -c %s'      # GNU stat
else
  getfilesize='stat -f %z'      # BSD stat
fi

set -e # exit on any error

if [ -d /live/image/boot/ ] ; then # until Grml versions <=2012.XX
  LIVE_PATH_MAIN='/live/image'
  LIVE_PATH_BOOT='/live/image/boot/'
else # for Grml versions >=2013.XX
  LIVE_PATH_MAIN='/lib/live/mount/medium/'
  LIVE_PATH_BOOT='/lib/live/mount/medium/boot/'
fi

VERSION='0.0.3'
GRML_LIVE_EDITOR=${VISUAL:-${EDITOR:-vi}}

# source core functions {{{
if ! [ -r /etc/grml/lsb-functions ] || ! [ -r /etc/grml/script-functions ] ; then
  echo "Error: could not read /etc/grml/lsb-functions and/or /etc/grml/script-functions." >&2
  echo "Error: $0 can run only in Grml live session. Exiting." >&2
  exit 1
fi

. /etc/grml/lsb-functions
. /etc/grml/script-functions
# }}}

if ! isgrmlcd ; then
  echo "Error: $0 can run only in Grml live session. Exiting." >&2
  exit 1
fi

# make sure we have what we need {{{
if check4progs mkisofs >/dev/null 2>&1 ; then
  MKISO=mkisofs
fi

if check4progs genisoimage >/dev/null 2>&1 ; then
  MKISO=genisoimage
fi

if [ -z "$MKISO" ] ; then
  echo "Error: neither mkisofs nor genisoimage available. Exiting." >&2
  exit 1
fi

check4progs stat || exit 1

# allow overriding via environment:
if [ -z "$MKSQUASHFS" ] ; then
  if which mksquashfs >/dev/null 2>&1 ; then
    MKSQUASHFS=mksquashfs
  else
    echo "Error: mksquashfs is not available. Exiting." >&2
    exit 1
  fi
fi
check4root || exit 1
# }}}

if [ -z "$1" ]; then
   echo "$0 - version $VERSION

Usage: $0 destination.iso
  destination.iso should point to a path that is on a hard disk,
  you might want to mount some swap partitions or swap files
  first, because grml-live-remaster will need a lot of RAM.

Please report bugs and feature requests: http://grml.org/bugs/" >&2
   exit 1
fi

if [ ! -r /remaster ]; then
  echo "Please create /remaster (e.g. link it to a harddrive)." >&2
  echo "Exiting to avoid running out of space on the live system." >&2
  exit 1
fi

mkdir -p /remaster/chroot /remaster/tmp /remaster/cdrom
mount -t tmpfs tmpfs /remaster/tmp
echo "#:# edit the following two lines to change the boot message" >/remaster/msg
echo "#:#" >>/remaster/msg
if [ -r ${LIVE_PATH_BOOT}/isolinux/boot.msg ] ; then
  sed 1,2d ${LIVE_PATH_BOOT}/isolinux/boot.msg >>/remaster/msg
fi

SQUASHFS_FILE="$(find ${LIVE_PATH_MAIN}/live -name \*.squashfs | head -1)"
if ! grep -q "/remaster/cdrom squashfs" /proc/mounts ;  then
   mount -t squashfs "$SQUASHFS_FILE" /remaster/cdrom -o ro,loop
fi

if ! grep -q "aufs /remaster/chroot" /proc/mounts ; then
   mount -t aufs aufs /remaster/chroot -o br:/remaster/tmp=rw:/remaster/cdrom=rr
fi

for i in run dev dev/pts proc root sys tmp; do
    mount --bind /$i /remaster/chroot/$i
done

echo "Now edit the contents of the live CD in this chrooted shell:"
chroot /remaster/chroot

for i in run dev/pts dev proc root sys tmp; do
        umount /remaster/chroot/$i
done

${GRML_LIVE_EDITOR} /remaster/msg

[ -d /remaster/iso ] || mkdir /remaster/iso

for i in ${LIVE_PATH_MAIN}/*; do
    if [ ! $i = ${LIVE_PATH_MAIN}/live ]; then
       cp -R $i /remaster/iso
    fi
done

if [ -r /remaster/iso/boot/isolinux/boot.msg ] ; then
   rm /remaster/iso/boot/isolinux/boot.msg
fi

# make sure we support usb sticks as well:
if [ -d ${LIVE_PATH_BOOT}/isolinux ] ; then
   BOOTSTUFF=${LIVE_PATH_BOOT}/isolinux
else
   BOOTSTUFF=${LIVE_PATH_MAIN}
fi

[ -d /remaster/iso/boot/isolinux ] || mkdir -p /remaster/iso/boot/isolinux

sed 3,4d "${BOOTSTUFF}"/boot.msg \
        >/remaster/iso/boot/isolinux/boot.msg
sed 1,2d /remaster/msg >>/remaster/iso/boot/isolinux/boot.msg

SQUASHFS_FQNAME=/remaster/iso/${SQUASHFS_FILE##$LIVE_PATH_MAIN}
mkdir -p $(dirname $SQUASHFS_FQNAME)
# the next line is necessary for grml2usb to work on the destination image
echo $(basename $SQUASHFS_FQNAME) > $(dirname $SQUASHFS_FQNAME)/filesystem.module
$MKSQUASHFS /remaster/chroot $SQUASHFS_FQNAME
umount /remaster/chroot /remaster/cdrom

if [ -f /remaster/iso/boot/isolinux/isolinux.bin ] ; then
   ISOLINUX=boot/isolinux/isolinux.bin
   ISOLINUX_BOOTCAT=boot/isolinux/boot.cat
else
   ISOLINUX=isolinux.bin
   ISOLINUX_BOOTCAT=boot.cat
fi

$MKISO -b $ISOLINUX -no-emul-boot -c $ISOLINUX_BOOTCAT \
        -boot-info-table -boot-load-size 4 -no-pad \
        -l -r -J -o "$1" /remaster/iso
# pad for partition table
siz=$($getfilesize "$1")
cyls=$((siz / 512 / 32 / 16 + 1))       # C=$cyls H=16 S=32 (= 256 KiB units)
siz=$((cyls * 16 * 32 * 512))           # size after padding
dd if=/dev/zero bs=1 count=1 seek=$((siz - 1)) of="$1" 2>/dev/null
rm -R /remaster/iso

# here is the place where we could apply bootgrub.mksh

echo ""
echo "ISO generation complete:"
ls --color -l "$1"
echo "If you want to customize your ISO, just call grml-live-remaster again."

## END OF FILE #################################################################
# vim: ai filetype=sh expandtab
