# This file was deployed via grml-live's
# ${GRML_FAI_CONFIG}/scripts/GRMLBASE/80-initramfs script, using
# ${GRML_FAI_CONFIG}/files/GRMLBASE/etc/grml/grml2ram.conf
#
# Filename:      /etc/grml/grml2ram.conf
# Purpose:       Inform grml2ram about squashfs setup
# Authors:       grml-team (grml.org),
#                (c) Chris Hofstaedtler <ch@grml.org>,
# Bug-Reports:   see http://grml.org/bugs/
# License:       This file is licensed under the GPL v2 or any later version.
################################################################################

LIVECD_PATH=/run/initramfs/live
MEDIA_PATH=/live/%GRML_NAME%
MEDIA_SQUASHFS_NAME=%SQUASHFS_NAME%
