#!/bin/sh
# Filename:      ~/.xinitrc.d/grml_wallpaper
# Purpose:       set wallpaper
# Authors:       grml-team (grml.org), (c) Michael Prokop <mika@grml.org>
# Bug-Reports:   see http://grml.org/bugs/
# License:       This file is licensed under the GPL v2 or any later version.
################################################################################

if [ "$XINIT_GRML_WALLPAPER" = "false" ] ; then
   exit 0
fi

# set wallpaper
[ -x /usr/bin/fbsetbg ] && [ -r /usr/share/grml/desktop.jpg ] && \
  fbsetbg -A /usr/share/grml/desktop.jpg &

## END OF FILE #################################################################
