#!/bin/sh
# Filename:      ~/.xinitrc.d/grml_wallpaper
# Purpose:       set wallpaper
# Authors:       grml-team (grml.org), (c) Michael Prokop <mika@grml.org>
# Bug-Reports:   see http://grml.org/bugs/
# License:       This file is licensed under the GPL v2 or any later version.
################################################################################

if [ "$XINIT_GRML_WALLPAPER" = "false" ] ; then
   exit 0
fi

# set wallpaper
# wmsetbg -t /usr/share/grml/desktop.png &
  if [ -x /usr/bin/Esetroot ] ; then
     [ -r /usr/share/grml/desktop.jpg ] && Esetroot -scale /usr/share/grml/desktop.jpg &
  fi

## END OF FILE #################################################################
