#!/bin/sh
# Filename:      ~/.xinitrc.d/grml_info
# Purpose:       start Grml's information screen
# Authors:       grml-team (grml.org), (c) Michael Prokop <mika@grml.org>
# Bug-Reports:   see http://grml.org/bugs/
# License:       This file is licensed under the GPL v2 or any later version.
################################################################################

if [ "$XINIT_GRML_INFO" = "false" ] ; then
  exit 0
fi

[ -r /etc/grml_cd ] && grml-info &

## END OF FILE #################################################################
