#!/bin/sh
set -u
set -e

if [ -r $target/usr/bin/xterm ] ; then
   $ROOTCMD update-alternatives --set x-terminal-emulator /usr/bin/xterm
fi

if [ -r $target/etc/X11/cursors/whiteglass.theme ] ; then
   $ROOTCMD update-alternatives --set x-cursor-theme /etc/X11/cursors/whiteglass.theme
fi
