-- This file has been generated by Ion. Do not edit.
return {
    [0] = {
        ["subs"] = {
            [1] = {
                ["type"] = "WIonWS",
                ["name"] = "WIonWS",
                ["switchto"] = true,
                ["split_tree"] = {
                    ["tls"] = 753,
                    ["tl"] = {
                        ["type"] = "WSplitRegion",
                        ["regparams"] = {
                            ["flags"] = 8,
                            ["type"] = "WFrame",
                            ["name"] = "WFrame",
                            ["subs"] = {
                                [1] = {
                                    ["type"] = "WClientWin",
                                    ["windowid"] = 8388620,
                                    ["switchto"] = true,
                                    ["checkcode"] = 1,
                                },
                            },
                            ["frame_style"] = "frame-tiled-ionws",
                            ["saved_h"] = 768,
                            ["saved_y"] = 0,
                        },
                    },
                    ["dir"] = "vertical",
                    ["brs"] = 15,
                    ["br"] = {
                        ["type"] = "WSplitST",
                    },
                    ["type"] = "WSplitSplit",
                },
            },
            [2] = {
                ["type"] = "WIonWS",
                ["name"] = "WIonWS<1>",
                ["split_tree"] = {
                    ["tls"] = 753,
                    ["tl"] = {
                        ["type"] = "WSplitRegion",
                        ["regparams"] = {
                            ["flags"] = 8,
                            ["type"] = "WFrame",
                            ["name"] = "WFrame<1>",
                            ["subs"] = {
                            },
                            ["frame_style"] = "frame-tiled-ionws",
                            ["saved_h"] = 768,
                            ["saved_y"] = 0,
                        },
                    },
                    ["dir"] = "vertical",
                    ["brs"] = 15,
                    ["br"] = {
                        ["type"] = "WSplitST",
                    },
                    ["type"] = "WSplitSplit",
                },
            },
        },
        ["type"] = "WScreen",
        ["name"] = "WScreen",
    },
}

