#!/bin/sh
# This file was deployed via grml-live's
# ${GRML_FAI_CONFIG}/scripts/GRMLBASE/80-initramfs script, using
# ${GRML_FAI_CONFIG}/files/GRMLBASE/usr/share/initramfs-tools/hooks/virtio-gpu
#
# Purpose: hook for adding virtio_gpu module to initramfs

set -e

# initramfs-tools header

PREREQ=""
prereqs()
{
        echo "${PREREQ}"
}

case "${1}" in
        prereqs)
                prereqs
                exit 0
                ;;
esac

. /usr/share/initramfs-tools/hook-functions

manual_add_modules virtio_gpu
