#!/bin/sh
# Filename:      ~/.xinitrc.d/grml_wallpaper
# Purpose:       set wallpaper
# Authors:       grml-team (grml.org), (c) Michael Prokop <mika@grml.org>
# Bug-Reports:   see http://grml.org/bugs/
# License:       This file is licensed under the GPL v2 or any later version.
################################################################################

if [ "$XINIT_GRML_WALLPAPER" = "false" ] ; then
   exit 0
fi

# set wallpaper
if ! [ -r /usr/share/grml/desktop.jpg ] ; then
  exit 0
fi

if command -v xwallpaper >/dev/null 2>&1 ; then
  xwallpaper --maximize /usr/share/grml/desktop.jpg &
elif command -v fbsetbg >/dev/null 2>&1 ; then
  fbsetbg -A /usr/share/grml/desktop.jpg &
fi

## END OF FILE #################################################################
