#!/bin/sh
# Filename:      ~/.xinitrc.d/grml_xsettings
# Purpose:       configuration of X settings
# Authors:       grml-team (grml.org), (c) Michael Prokop <mika@grml.org>
# Bug-Reports:   see http://grml.org/bugs/
# License:       This file is licensed under the GPL v2 or any later version.
################################################################################

if [ "$XINIT_GRML_XSETTINGS" = "false" ] ; then
   exit 0
fi

# set default cursor
  xsetroot -cursor_name left_ptr

## set mouse speed behaviour:
# fast:
# xset m 4 2
# normal:
  xset m 2 5
# slow:
# xset m 1 1

# other settings:
# xset m 20/10 4

# disable screensaver and dpms:
# xset s off
# xset -dpms

# xresources
  [ -r "$HOME"/.Xresources ] && xrdb -merge "$HOME"/.Xresources

## END OF FILE #################################################################
