#!/bin/sh
# Filename:      grml-misc
# Purpose:       initialize misc stuff on grml system
# Authors:       grml-team (grml.org), (c) Michael Prokop <mika@grml.org>
# Bug-Reports:   see http://grml.org/bugs/
# License:       This file is licensed under the GPL v2.
# Latest change: Sam Mai 27 14:43:56 CEST 2006 [mika]
################################################################################

if grep -q nocolor /proc/cmdline ; then
   RC_NOCOLOR=yes
   . /etc/grml/lsb-functions
else
   . /etc/grml/lsb-functions
fi

# finished booting
einfo "Finished execution of main grml startup." ; eend 0

## END OF FILE #################################################################
