#!/bin/sh
# Filename:      postrm
# Purpose:       postrm script for package grml-etc
# Authors:       grml-team (grml.org), (c) Michael Prokop <mika@grml.org>
# Bug-Reports:   see http://grml.org/bugs/
# License:       This file is licensed under the GPL v2.
################################################################################

set -e

TO_UNDIVERT1="ssh"

undivert_gen() {
    DEXT=${3:-original}
    dpkg-divert --remove --rename --package grml-etc \
        --divert $2/$1.$DEXT $2/$1 #> /dev/null
}

replace_grml_with_orig_inittab() {
  if grep -q '^l0:0:wait:/etc/init.d/grml-halt$' /etc/inittab ; then
     sed -i 's|^l0:0:wait:/etc/init.d/grml-halt|l0:0:wait:/etc/init.d/rc 0|' /etc/inittab
  fi

  if grep -q '^l6:6:wait:/etc/init.d/grml-reboot$' /etc/inittab ; then
     sed -i 's|^l6:6:wait:/etc/init.d/grml-reboot|l6:6:wait:/etc/init.d/rc 6|' /etc/inittab
  fi
}

case "$1" in
    purge)
        for cmd in $TO_UNDIVERT1; do
                undivert_gen $cmd /etc/init.d
        done

	# make sure the ssh init script even exists if something is failing...
	if ls /etc/init.d/ssh* 1>/dev/null 2>&1 ; then
	  if [ ! -f /etc/init.d/ssh -a /etc/init.d/ssh.original.dpkg-new ] ; then
	     mv /etc/init.d/ssh.original.dpkg-new /etc/init.d/ssh
	  fi
	fi

	replace_grml_with_orig_inittab
     ;;

   remove|abort-install|disappear)
        replace_grml_with_orig_inittab
     ;;

   upgrade|failed-upgrade|abort-install|abort-upgrade)
     ;;

    *)
      echo "postrm called with unknown argument $1" >&2
      exit 1
esac

#DEBHELPER#

exit 0

## END OF FILE #################################################################
