#!/bin/bash
# Filename:      ${GRML_FAI_CONFIG}/scripts/GRMLBASE/00-networkd-dhcp-fallback
# Purpose:       configure systemd-networkd for the live-system
# Authors:       (c) Christopher Bock <christopher@bocki.com>
# Bug-Reports:   see http://grml.org/bugs/
# License:       This file is licensed under the GPL v2 or any later version.
################################################################################

set -u
set -e

fcopy -M -v /etc/systemd/network/99-dhcp-fallback.network

## END OF FILE #################################################################
# vim:ft=sh expandtab ai tw=80 tabstop=4 shiftwidth=2
