#!/bin/bash
# Filename:      ${GRML_FAI_CONFIG}/scripts/GRMLBASE/01-autoconfig
# Purpose:       install grml autoconfig files
# Authors:       grml-team (grml.org), (c) Michael Prokop <mika@grml.org>
# Bug-Reports:   see http://grml.org/bugs/
# License:       This file is licensed under the GPL v2 or any later version.
################################################################################

set -u
set -e

# FAI sets $target, but shellcheck does not know that.
target=${target:?}

fcopy -M -i -B -v -r /etc/grml
fcopy -M -i -B -v /etc/dhcp/dhclient-exit-hooks.d/grml-sethostname
fcopy -M -i -B -v /etc/modules-load.d/grml-autoconfig.conf
fcopy -M -i -B -v /etc/systemd/system/grml-autoconfig.service
fcopy -M -i -B -v /usr/bin/restore-config
fcopy -M -i -B -v /usr/bin/save-config
fcopy -M -i -B -v /usr/sbin/grml-autoconfig
fcopy -M -i -B -v /usr/share/grml-autoconfig/grml-autoconfig

## END OF FILE #################################################################
# vim:ft=sh expandtab ai tw=80 tabstop=4 shiftwidth=2
