#!/bin/bash
# Filename:      ${GRML_FAI_CONFIG}/scripts/GRMLBASE/26-console-setup
# Purpose:       console-setup configuration of the live system
# Authors:       grml-team (grml.org), (c) Michael Prokop <mika@grml.org>
# Bug-Reports:   see http://grml.org/bugs/
# License:       This file is licensed under the GPL v2 or any later version.
################################################################################

set -u
set -e

fcopy -M -v /etc/default/console-setup

# Have setupcon write its cache into /etc/console-setup, to avoid doing
# this on each live boot.
rm -f "${target}"/etc/console-setup/cached*
$ROOTCMD setupcon --save-only

## END OF FILE #################################################################
# vim:ft=sh expandtab ai tw=80 tabstop=4 shiftwidth=2
