#!/bin/bash
# Filename:      ${GRML_FAI_CONFIG}/scripts/GRMLBASE/42-branding
# Purpose:       install branding files
# Authors:       grml-team (grml.org), (c) Michael Prokop <mika@grml.org>
# Bug-Reports:   see http://grml.org/bugs/
# License:       This file is licensed under the GPL v2 or any later version.
################################################################################

set -u
set -e

# FAI sets $target, but shellcheck does not know that.
target=${target:?}

# shellcheck source=/dev/null
. "$GRML_LIVE_CONFIG"

os_release_file="${target}"/etc/os-release
rm -f "${os_release_file}"
cat <<EOT > "${os_release_file}"
PRETTY_NAME="${RELEASE_INFO}"
NAME="${DISTRI_NAME}"
VERSION="${VERSION}"
ID="${DISTRI_INFO}"
HOME_URL="https://grml.org/"
EOT

fcopy -m root,root,0755 -v /usr/share/initramfs-tools/scripts/init-top/grml
fcopy -M -v /usr/share/doc/grml-docs/startpage.html

## END OF FILE #################################################################
# vim:ft=sh expandtab ai tw=80 tabstop=4 shiftwidth=2
