#!/bin/sh
# Filename:      ${GRML_FAI_CONFIG}/scripts/GRMLBASE/80-initramfs
# Purpose:       configure initramfs and rebuild it
# Authors:       grml-team (grml.org)
# Bug-Reports:   see http://grml.org/bugs/
# License:       This file is licensed under the GPL v2 or any later version.
################################################################################

set -u
set -e

# FAI sets $target, but shellcheck does not know that.
target=${target:?}

fcopy -M -v /etc/dracut.conf.d/55-grml-live.conf
# Set default "kernel" command line
fcopy -M -v /etc/dracut.conf.d/55-grml-live-cmdline.conf
grml-live-adjust-boot-files "${target}"/etc/dracut.conf.d/55-grml-live-cmdline.conf
# write grml2ram.conf so it knows where the squashfs is
fcopy -M -v /etc/grml/grml2ram.conf
grml-live-adjust-boot-files "${target}"/etc/grml/grml2ram.conf

fcopy -M -v -r /usr/lib/dracut

$ROOTCMD update-initramfs -k all -d
$ROOTCMD update-initramfs -k all -c

$ROOTCMD find /boot/ -name initrd\*.bak -exec rm {} \;

# dracut makes the initrd images o-rx
$ROOTCMD find /boot/ -name initrd.img* -exec chmod 0644 {} \;
