#!/bin/bash
# Filename:      ${GRML_FAI_CONFIG}/scripts/GRMLBASE/96-apt-listbugs
# Purpose:       retrieve list of bugreports of installed packages inside chroot
# Authors:       grml-team (grml.org), (c) Michael Prokop <mika@grml.org>
# Bug-Reports:   see http://grml.org/bugs/
# License:       This file is licensed under the GPL v2 or any later version.
################################################################################

set -u
set -e

# FAI sets $target, but shellcheck does not know that.
target=${target:?}

if [ -r "$target"/etc/apt/apt.conf.d/10apt-listbugs ] ; then
  if [ -x "$target"/usr/sbin/apt-listbugs ] ; then
    sed -i 's#//DPkg::#DPkg::#' "$target"/etc/apt/apt.conf.d/10apt-listbugs
  fi
fi

set +u
if ifclass RELEASE ; then
set -u
  if [ -x "$target"/usr/sbin/apt-listbugs ] && [ -x "$target"/usr/bin/apt-show-source ] && \
     [ -x "$target"/etc/apt/grml/listbugs ] ; then
     for severity in critical grave serious ; do
         SEVERITY=$severity $ROOTCMD /etc/apt/grml/listbugs > \
         "$LOGDIR/bugs.${severity}" || true # make sure it does not fail
     done
  fi

fi

## END OF FILE #################################################################
# vim:ft=sh expandtab ai tw=80 tabstop=4 shiftwidth=2
