#!/bin/bash
# Filename:      ${GRML_FAI_CONFIG}/scripts/GRMLBASE/99-finish-grml-build
# Purpose:       finalize grml chroot build
# Authors:       grml-team (grml.org), (c) Michael Prokop <mika@grml.org>
# Bug-Reports:   see http://grml.org/bugs/
# License:       This file is licensed under the GPL v2 or any later version.
################################################################################

set -u
set -e

# FAI sets $target, but shellcheck does not know that.
target=${target:?}

# remove an existing /etc/debian_chroot file:
if [ -r "$target"/etc/debian_chroot ] ; then
   rm -f "$target"/etc/debian_chroot
fi

# /etc/grml_cd makes the live system recognizable as a live system
touch "$target"/etc/grml_cd

## END OF FILE #################################################################
# vim:ft=sh expandtab ai tw=80 tabstop=4 shiftwidth=2
