#!/bin/bash
# Filename:      ${GRML_FAI_CONFIG}/media-scripts/GRMLBASE/90-branding
# Purpose:       Install GRML branding files
# Authors:       grml-team (grml.org)
# Bug-Reports:   see http://grml.org/bugs/
# License:       This file is licensed under the GPL v2 or any later version.
################################################################################

set -u
set -e

# FAI sets $target, but shellcheck does not know that.
target=${target:?}
# shellcheck source=/dev/null
. "$GRML_LIVE_CONFIG"

# Remove files from a previous run.
$ROOTCMD rm -rf "${GRML_LIVE_MEDIADIR}/GRML/${GRML_NAME}"
$ROOTCMD mkdir -p "${GRML_LIVE_MEDIADIR}/GRML"

grml-live-command copy-media-files media -r "/GRML/GRML_NAME"

if $ROOTCMD test -r "${GRML_LIVE_MEDIADIR}"/GRML/GRML_NAME/grml-version ; then
  $ROOTCMD sed -i \
    -e "s/%RELEASE_INFO%/$RELEASE_INFO/" \
    -e "s/%DATE%/$DATE/" \
    "${GRML_LIVE_MEDIADIR}"/GRML/GRML_NAME/grml-version
fi

# Now rename to the correct ${GRML_NAME} name.
$ROOTCMD mv "${GRML_LIVE_MEDIADIR}"/GRML/GRML_NAME/ "${GRML_LIVE_MEDIADIR}/GRML/${GRML_NAME}"

## END OF FILE #################################################################
# vim:ft=sh expandtab ai tw=80 tabstop=4 shiftwidth=2
