#!/usr/bin/env python3
import argparse
import os
import re
import subprocess
import sys
from pathlib import Path

IGNORED_PEOPLE = set(
    "GitHub",
)


class Listener:
    def __init__(self):
        self.failed = False

    def error(self, message: str):
        raise NotImplementedError

    def info(self, message: str):
        raise NotImplementedError

    def warn(self, message: str):
        raise NotImplementedError


class CliListener(Listener):
    def error(self, message: str):
        self.failed = True
        sys.stderr.write(f"E: {message}\n")

    def info(self, message: str):
        sys.stdout.write(f"I: {message}\n")

    def warn(self, message: str):
        sys.stdout.write(f"W: {message}\n")


def run_x(args, check: bool = True, **kwargs):
    # str-ify Paths, not necessary, but for readability in logs.
    args = [arg if isinstance(arg, str) else str(arg) for arg in args]
    args_str = '" "'.join(args)
    print(f'D: Running "{args_str}"', flush=True)
    return subprocess.run(args, check=check, **kwargs)


def parse_package_list(s: str) -> dict:
    package_dict = {}
    for line in s.split("\n"):
        match = re.match(r"^ii\s+(\S+)\s+(\S+)\s", line)
        if match:
            package_dict[match[1]] = match[2]
    return package_dict


def sort_people(people: list[str]) -> list[str]:
    """Sort list of names, ignoring case"""
    return sorted(people, key=lambda v: v.upper())


def unique_case_insensitive(strings: list[str]):
    seen = set()
    unique_strings = []
    for string in strings:
        upper = string.upper()
        if upper in seen:
            continue
        seen.add(upper)
        unique_strings.append(string)
    return unique_strings


def format_package_block(package: str, range_label: str, is_new: bool, commits: list[str], people: list[str]) -> str:
    new_marker = "(new)" if is_new else ""
    commit_list = "\n    ".join(commits)
    people_list = "\n    ".join(sort_people(people))
    return f"""Package {package}: {range_label} {new_marker}
    {commit_list}
People:
    {people_list}
------------------------------------------------------------------------
"""


def build_changes(
    output_filename: Path,
    dpkg_list_new: Path,
    dpkg_list_old: Path,
    package_prefix: str,
    git_url_base: str,
    git_repo_workspace: Path,
    job_name: str,
    build_id: str,
    listener: Listener,
):
    git_repo_workspace.mkdir(parents=True, exist_ok=True)
    all_people = []

    changelog = f"""------------------------------------------------------------------------
Generated by CI for job {job_name} {build_id}
------------------------------------------------------------------------
"""

    if not dpkg_list_new.exists():
        listener.error(f"Could not read package list {dpkg_list_new}")
        return

    packages = parse_package_list(dpkg_list_new.read_text())
    packages_old = {}
    try:
        packages_old = parse_package_list(dpkg_list_old.read_text())
    except Exception as e:
        listener.info(f"While parsing old package list: {e}")

    debian_changes = {"removed": [], "added": [], "changed": []}

    for package in set(packages_old) - set(packages):
        if re.match(f"^{package_prefix}", package):
            changelog += f"""Package {package}: Removed.
------------------------------------------------------------------------
"""
        else:
            debian_changes["removed"].append(package)

    for package, version in packages.items():
        old_version = packages_old.get(package)
        if re.match(f"^{package_prefix}", package):
            try:
                listener.info(f"Generating changes list for package {package}...")
                if old_version:
                    listener.info(f"Version {old_version} -> {version}")
                    if old_version == version:
                        continue

                git_url = f"{git_url_base}/{package}"
                gitpath = fetch_grml_package_repo(git_repo_workspace, package, git_url)

                if old_version:
                    base_tag = f"v{old_version}"
                    range = f"{base_tag}..v{version}"
                else:
                    base_tag = None
                    range = f"v{version}"

                commits, people = get_grml_package_changes(gitpath, base_tag, range)
                people = [person for person in people if person not in IGNORED_PEOPLE]
                all_people.extend(people)
                changelog += format_package_block(
                    package,
                    range,
                    is_new=not old_version,
                    commits=commits,
                    people=people,
                )
            except Exception as e:
                listener.warn(f"Generating change report for package {package} failed: {e}")
                changelog += f"""Package {package}: [failed]
------------------------------------------------------------------------
"""

        else:
            if old_version:
                if old_version == version:
                    continue
                debian_changes["changed"].append(f"{package} {old_version} -> {version}")
            else:
                debian_changes["added"].append(package)

    all_people = unique_case_insensitive(all_people)
    all_people_list = "\n    ".join(sort_people(all_people))
    changelog += f"""All involved people:
    {all_people_list}
------------------------------------------------------------------------
"""

    changelog += """Changes to Debian package list:
  Added:
    {}
  Changed:
    {}
  Removed:
    {}
------------------------------------------------------------------------
""".format(
        "\n    ".join(sorted(debian_changes["added"])).strip(),
        "\n    ".join(sorted(debian_changes["changed"])).strip(),
        "\n    ".join(sorted(debian_changes["removed"])).strip(),
    )

    output_filename.write_text(changelog)


def single_repo_changes(repo: Path, tag: str, package: str | None, listener: Listener):
    if not repo.is_dir():
        listener.error(f"Repo path is not a directory: {repo}")
        return

    check = subprocess.run(
        ["git", "rev-parse", "--git-dir"],
        cwd=repo,
        capture_output=True,
    )
    if check.returncode != 0:
        listener.error(f"Not a git repository: {repo}")
        return

    verify = subprocess.run(
        ["git", "rev-parse", "--verify", "--quiet", f"{tag}^{{commit}}"],
        cwd=repo,
        capture_output=True,
    )
    if verify.returncode != 0:
        listener.error(f"Tag not found in {repo}: {tag}")
        return

    range_arg = f"{tag}..HEAD"
    package_name = package or repo.resolve().name

    commits, people = get_grml_package_changes(repo, tag, range_arg)
    people = [p for p in people if p not in IGNORED_PEOPLE]
    people = unique_case_insensitive(people)

    block = format_package_block(
        package_name,
        range_arg,
        is_new=False,
        commits=commits,
        people=people,
    )
    sys.stdout.write(block)


def main() -> int:
    parser = argparse.ArgumentParser()
    subparsers = parser.add_subparsers(dest="mode", required=True)

    p_build = subparsers.add_parser(
        "build",
        help="generate per-package CI report based on dpkg lists",
    )
    p_build.add_argument("output_filename")
    p_build.add_argument("dpkg_list_new")
    p_build.add_argument("dpkg_list_old")
    p_build.add_argument("package_prefix")
    p_build.add_argument("git_url_base")
    p_build.add_argument("git_repo_workspace")
    p_build.add_argument("job_name")
    p_build.add_argument("build_id")

    p_repo = subparsers.add_parser(
        "repo",
        help="generate changelog block for a single already-checked-out repo",
    )
    p_repo.add_argument(
        "repo",
        type=Path,
        help="path to a checked-out git repository",
    )
    p_repo.add_argument(
        "tag",
        help="base tag; commits in TAG..HEAD are listed",
    )
    p_repo.add_argument(
        "--package",
        help="package name to use in the output (default: repo directory basename)",
    )

    args = parser.parse_args()
    listener = CliListener()

    try:
        if args.mode == "build":
            build_changes(
                Path(args.output_filename),
                Path(args.dpkg_list_new),
                Path(args.dpkg_list_old),
                args.package_prefix,
                args.git_url_base,
                Path(args.git_repo_workspace),
                args.job_name,
                args.build_id,
                listener,
            )
        elif args.mode == "repo":
            single_repo_changes(
                args.repo,
                args.tag,
                args.package,
                listener,
            )
    except Exception as except_inst:
        listener.error(f"Uncaught exception: {except_inst}")

    if listener.failed:
        return 1
    return 0


def fetch_grml_package_repo(git_repo_workspace: Path, package: str, git_url: str) -> Path:
    """Clone and update git repository."""
    gitpath = git_repo_workspace / f"{package}.git"
    if not gitpath.exists():
        env = dict(os.environ) | {"GIT_TERMINAL_PROMPT": "0"}
        run_x(
            ["git", "clone", "--bare", "--single-branch", git_url, gitpath],
            cwd=git_repo_workspace,
            env=env,
        )
    if not gitpath.exists():
        raise Exception("Repository not found")

    # update repo
    run_x(["git", "remote", "set-url", "origin", git_url], cwd=gitpath)
    run_x(["git", "remote", "update", "--prune"], cwd=gitpath).check_returncode()
    return gitpath


def get_grml_package_changes(
    gitpath: Path,
    base_tag: str | None,
    range: str,
) -> tuple[list[str], list[str]]:
    """
    Return (commit_lines, people) for non-merge commits in `range` of `gitpath`.

    If `base_tag` is given, drop commits that came in via merges of unrelated
    histories (e.g. another repo absorbed into this one): a commit is kept iff
    it shares a common ancestor with `base_tag`, or it was authored after
    `base_tag` (the latter keeps integration commits authored on top of an
    imported branch before its merge into mainline).
    """
    trailers = ["Thanks", "Reported-By"]

    enum_log = run_x(
        ["git", "log", "--no-merges", "--pretty=format:%H %at", range],
        cwd=gitpath,
        capture_output=True,
    )
    candidates: list[tuple[str, int]] = []
    for line in enum_log.stdout.decode().splitlines():
        line = line.strip()
        if not line:
            continue
        hash, ts = line.split(" ", 1)
        candidates.append((hash, int(ts)))

    if base_tag:
        tag_ts_out = subprocess.run(
            ["git", "log", "-1", "--format=%at", base_tag],
            cwd=gitpath,
            capture_output=True,
            check=True,
        )
        tag_ts = int(tag_ts_out.stdout.decode().strip())
        kept_hashes: list[str] = []
        for hash, ts in candidates:
            mergebase_proc = subprocess.run(
                ["git", "merge-base", base_tag, hash],
                cwd=gitpath,
                capture_output=True,
            )
            if mergebase_proc.returncode == 0 or ts > tag_ts:
                kept_hashes.append(hash)
    else:
        kept_hashes = [hash for hash, _ in candidates]

    if not kept_hashes:
        return [], []

    git_format = "--format=tformat:Commit: %H %s%nAuthor: %aN%nCommitter: %cN%n"
    for trailer in trailers:
        git_format += f"%(trailers:key={trailer})%n"

    git_log = run_x(
        ["git", "log", "--no-walk=unsorted", git_format, *kept_hashes],
        cwd=gitpath,
        capture_output=True,
    )

    changes = []
    people = []
    for line in git_log.stdout.decode().splitlines():
        line = line.strip()
        if not line:
            continue
        key, value = line.split(": ", 1)
        if key == "Commit":
            changes.append(value)
        else:
            people.append(value)

    return changes, unique_case_insensitive(people)


if __name__ == "__main__":
    sys.exit(main())
