#!/bin/bash
# Filename:      ${GRML_FAI_CONFIG}/config/scripts/GRML_FULL/01-firefox
# Purpose:       set startpage of Firefox and further configuration defaults
# Authors:       grml-team (grml.org), (c) Michael Prokop <mika@grml.org>
# Bug-Reports:   see http://grml.org/bugs/
# License:       This file is licensed under the GPL v2 or any later version.
################################################################################

set -u
set -e

fcopy -M -i -B -v /etc/firefox-esr/firefox-esr.js

## END OF FILE #################################################################
# vim:ft=sh expandtab ai tw=80 tabstop=4 shiftwidth=2
