#!/bin/bash
# Filename:      ${GRML_FAI_CONFIG}/config/scripts/GRML_FULL/01-iceweasel
# Purpose:       add startpage to Iceweasel
# Authors:       grml-team (grml.org), (c) Michael Prokop <mika@grml.org>
# Bug-Reports:   see http://grml.org/bugs/
# License:       This file is licensed under the GPL v2 or any later version.
################################################################################

set -u
set -e

fcopy -v /etc/iceweasel/profile/prefs.js

## END OF FILE #################################################################
# vim:ft=sh expandtab ai tw=80 tabstop=4 shiftwidth=2
