#!/bin/bash
# Filename:      ${GRML_FAI_CONFIG}/config/scripts/DEBORPHAN/10-whitelist
# Purpose:       whitelist packages to keep with deborphan
# Authors:       grml-team (grml.org), (c) Michael Prokop <mika@grml.org>
# Bug-Reports:   see http://grml.org/bugs/
# License:       This file is licensed under the GPL v2 or any later version.
################################################################################

set -u
set -e

# workaround for dnsutils transitional package, we can drop this as soon as the
# bind9-dnsutils package is available in all our supported Debian releases
if [[ -r "${target}/usr/share/doc/dnsutils" ]] && [ -x "${target}/usr/bin/deborphan" ] ; then
  echo "Adding dnsutils to deborphan whitelist"
  $ROOTCMD deborphan --add-keep dnsutils || /bin/true
fi

## END OF FILE #################################################################
# vim:ft=sh expandtab ai tw=80 tabstop=4 shiftwidth=2
