#!/bin/bash
# Filename:      ${GRML_FAI_CONFIG}/config/scripts/DEBORPHAN/98-clean-chroot
# Purpose:       drop as many packages from grml as possible
# Authors:       (c) Michael Prokop <mika@grml.org>
# Bug-Reports:   see http://grml.org/bugs/
# License:       This file is licensed under the GPL v2.
################################################################################

set -u
set -e

if ! [ -x $target/usr/bin/deborphan ] ; then
  echo "Warning: deborphan not installed"
  exit 0
fi

# remove all packages not necessary anymore:
echo "Executing apt-get -y --purge autoremove"
$ROOTCMD apt-get -y --purge autoremove

# remove packages until deborphan does not find anymore:
while [ "$($ROOTCMD deborphan)" != "" ] ; do
  echo "Executing deborphan"
  $ROOTCMD apt-get -y --purge remove $($ROOTCMD deborphan)
done

# make sure we don't have any removed but not-yet-purged packages left,
# otherwise GRMLBASE/03-get-sources might try to download unavailable
# packages and will fail doing so
PURGE_PACKAGES=$($ROOTCMD dpkg --list | awk '/^rc/ {print $2}')

if [ -n "$PURGE_PACKAGES" ] ; then
  echo "Getting rid of packages which have been removed but not yet purged: $PURGE_PACKAGES"
  $ROOTCMD dpkg --purge $PURGE_PACKAGES
fi

## END OF FILE #################################################################
# vim:ft=sh expandtab ai tw=80 tabstop=4 shiftwidth=2
