#!/bin/zsh
# Filename:      grml-live
# Purpose:       build script for creating grml live-cd
# Authors:       grml-team (grml.org), (c) Michael Prokop <mika@grml.org>
# Bug-Reports:   see http://grml.org/bugs/
# License:       This file is licensed under the GPL v2.
# Latest change: Thu Feb 08 22:35:43 CET 2007
################################################################################

LANG=C
LC_ALL=C

DEBUG=1        # be more verbose on stdout?
DEBUG_SYSLOG=1 # log actions to syslog?

# functions
FUNCTIONSFILE='functions.sh'

for file in $FUNCTIONSFILE /etc/grml/lsb-functions  /etc/grml/script-functions ; do
    [[ -r $FUNCTIONSFILE ]] && source $file || { print "Reading $file failed, fatal error, exiting." ; exit 1 }
done

trap bailout 1 2 3 15

# main execution
debug "executing cmdline_options" ; cmdline_options

## END OF FILE #################################################################
# vim: ai tw=80 ft=zsh expandtab
