#!/bin/zsh
# Filename:      grml-live
# Purpose:       
# Authors:       grml-team (grml.org), (c) Michael Prokop <mika@grml.org>
# Bug-Reports:   see http://grml.org/bugs/
# License:       This file is licensed under the GPL v2.
# Latest change: Thu Feb 08 21:06:07 CET 2007
################################################################################

echo TODO

## END OF FILE #################################################################
