#!/bin/bash
# Filename:      ${GRML_FAI_CONFIG}/scripts/GRML_FULL/44-grml-tools-xorg
# Purpose:       install graphical grml tools
# Authors:       grml-team (grml.org), (c) Michael Prokop <mika@grml.org>
# Bug-Reports:   see http://grml.org/bugs/
# License:       This file is licensed under the GPL v2 or any later version.
################################################################################

set -u
set -e

fcopy -m root,root,0755 /usr/bin/grml-resolution

## END OF FILE #################################################################
# vim:ft=sh expandtab ai tw=80 tabstop=4 shiftwidth=2
