#!/bin/bash
# Filename:      ${GRML_FAI_CONFIG}/config/scripts/GRMLBASE/02-run
# Purpose:       cleanup after initscripts postinst for /run
# Authors:       grml-team (grml.org)
# Bug-Reports:   see https://grml.org/bugs/
# License:       This file is licensed under the GPL v2 or any later version.
################################################################################

set -u
set -e

# This is what initscripts would do if everything would be fine.
if [ -L "$target/run" ] ; then
   rm -f "$target/run"
   rm -f -r "$target/var/run"
   rm -f -r "$target/var/lock"
   mkdir "$target/run"
   mkdir "$target/run/lock"
   chmod 1777 "$target/run/lock"
   ln -s -f /run "$target/var/run"
   ln -s -f /run/lock "$target/var/lock"
fi

## END OF FILE #################################################################
# vim:ft=sh expandtab ai tw=80 tabstop=4 shiftwidth=2
