#!/bin/bash
# Filename:      ${GRML_FAI_CONFIG}/config/scripts/GRMLBASE/03-get-sources
# Purpose:       download sources of Debian packages
# Authors:       grml-team (grml.org), (c) Michael Prokop <mika@grml.org>
# Bug-Reports:   see http://grml.org/bugs/
# License:       This file is licensed under the GPL v2 or any later version.
################################################################################

if ifclass SOURCES ; then
  echo "Class SOURCES set, retrieving source packages."
else
  echo "Class SOURCES not set, nothing to do."
  exit 0
fi

set -u

PACKAGE_LIST=$(mktemp)
SOURCES_PATH=/grml-live/grml_sources/
SOURCES_ERRORS_LOG="${SOURCES_PATH}"errors.log

bailout() {
  rm -f "${target}${SOURCES_ERRORS_LOG}"
  rm -f "$PACKAGE_LIST"
}

$ROOTCMD apt-get update

$ROOTCMD dpkg-query -W -f='${Package}\n' > "${PACKAGE_LIST}"

if ! [ -r "${PACKAGE_LIST}" ] ; then
  echo "Can not read ${PACKAGE_LIST}, can not download source packages as requested." >&2
  bailout
  exit 1
else
  mkdir -p "${target}${SOURCES_PATH}"

  # needs to be done for each package to get:
  # | Picking 'acpi-support' as source package instead of 'acpi-fakekey'
  # instead of:
  # | E: Unable to find a source package for acpi-fakekey
  for package in $(grep -v '^#' ${PACKAGE_LIST}) ; do
    cat << EOT | chroot "$target" /bin/bash
cd "${SOURCES_PATH}"
apt-get --download-only source "$package" 2>>"${SOURCES_ERRORS_LOG}"
EOT
  done

  if grep -q '^E:' "${target}${SOURCES_ERRORS_LOG}" ; then
    echo "Errors noticed while retrieving sources:" >&2
    cat "${target}${SOURCES_ERRORS_LOG}" >&2
    bailout
    exit 1
  elif grep -q '^W:' "${target}${SOURCES_ERRORS_LOG}" ; then
    echo "Warnings noticed while retrieving sources (not failing the build though):"
    cat "${target}${SOURCES_ERRORS_LOG}"
  elif grep -q '.' "${target}${SOURCES_ERRORS_LOG}" ; then
    echo "Unclassified problems noticed while retrieving sources:" >&2
    cat "${target}${SOURCES_ERRORS_LOG}" >&2
    bailout
    exit 1
  fi

fi

bailout

## END OF FILE #################################################################
# vim:ft=sh expandtab ai tw=80 tabstop=4 shiftwidth=2
