#!/bin/sh
# Filename:      /etc/grml/fai/config/scripts/GRMLBASE/05-hostname
# Purpose:       set hostname of live-system
# Authors:       grml-team (grml.org), (c) Michael Prokop <mika@grml.org>
# Bug-Reports:   see http://grml.org/bugs/
# License:       This file is licensed under the GPL v2 or any later version.
################################################################################

set -u
set -e

HOSTNAME=''
[ -r /etc/grml/grml-live.conf ]  && . /etc/grml/grml-live.conf
[ -r /etc/grml/grml-live.local ] && . /etc/grml/grml-live.local
[ -n "$HOSTNAME" ] || HOSTNAME=grml
echo "$HOSTNAME" > $target/etc/hostname

if [ -r $target/etc/postfix/main.cf ] ; then
  sed -i "s/^mydestination = .*/mydestination = $HOSTNAME, localhost, localhost.localdomain/" $target/etc/postfix/main.cf
  sed -i "s/^myhostname = .*/myhostname = $HOSTNAME/" $target/etc/postfix/main.cf
  echo "postfix postfix/mailname     string $HOSTNAME" | $ROOTCMD debconf-set-selections
  echo "postfix postfix/destinations string ${HOSTNAME}, localhost.grml.org, localhost" \
  | $ROOTCMD debconf-set-selections
fi

## END OF FILE #################################################################
# vim:ft=sh expandtab ai tw=80 tabstop=4 shiftwidth=3
