#!/bin/sh
# Filename:      /etc/grml/fai/config/scripts/GRMLBASE/10-build-initramfs
# Purpose:       configure live-initramfs and build initramfs for booting
# Authors:       grml-team (grml.org), (c) Michael Prokop <mika@grml.org>
# Bug-Reports:   see http://grml.org/bugs/
# License:       This file is licensed under the GPL v2 or any later version.
################################################################################

set -e

if ! [ -f "$target/etc/live.conf" ] ; then
  echo "Warning: $target/etc/live.conf does not exist yet,"
  echo "         ... installing /etc/grml/fai/live-initramfs/live.conf"
  cp /etc/grml/fai/live-initramfs/live.conf "$target/etc/live.conf"
fi

if [ -f /etc/grml/fai/live-initramfs/grml-script.init-top ] ; then
  cp /etc/grml/fai/live-initramfs/grml-script.init-top "$target/usr/share/initramfs-tools/scripts/init-top/grml"
else
  echo "Warning: /etc/grml/fai/live-initramfs/grml-script.init-top could not be read"
fi

FILE=$(ls -1 $target/boot/vmlinuz-* 2>/dev/null| sort -r | head -1)
KERNELVERSION=$(echo "${FILE##$target/boot/vmlinuz-}")

# make sure mdadm isn't executed in initrd:
#if [ -f "$target"/etc/default/mdadm ] ; then
#   sed -i "s/START_DAEMON=.*/START_DAEMON=false/" "$target"/etc/default/mdadm
#   sed -i "s/INITRDSTART=.*/INITRDSTART=none/"    "$target"/etc/default/mdadm
#fi

if [ -z "$KERNELVERSION" ] ; then
   echo "Error: No kernel found, can not create initramfs. Exiting.">&2
   exit 1
fi

if [ -f $target/usr/share/initramfs-tools/scripts/live ] ; then
   $ROOTCMD update-initramfs -c -t -k $KERNELVERSION
else
   echo "Error: live-initramfs does not seem to be present, can not create initramfs. Exiting.">&2
   exit 1
fi

## END OF FILE #################################################################
# vim:ft=sh expandtab ai tw=80 tabstop=4 shiftwidth=3
