#!/bin/sh
# Filename:      /etc/grml/fai/config/scripts/GRML/15-initsetup
# Purpose:       configure init system for the live-system
# Authors:       grml-team (grml.org), (c) Michael Prokop <mika@grml.org>
# Bug-Reports:   see http://grml.org/bugs/
# License:       This file is licensed under the GPL v2 or any later version.
# Latest change: Sun Sep 16 22:57:36 CEST 2007 [mika]
################################################################################

set -u
set -e

if grep -q 'small' $target/etc/grml_version ; then
   cp $target/etc/runlevel.conf.livecd.small $target/etc/runlevel.conf
else
   cp $target/etc/runlevel.conf.livecd $target/etc/runlevel.conf
fi

## END OF FILE #################################################################
# vim:ft=sh expandtab ai tw=80 tabstop=4 shiftwidth=3
