#!/bin/bash
# Filename:      ${GRML_FAI_CONFIG}/config/scripts/GRMLBASE/16-depmod
# Purpose:       set up kernel's modules.dep
# Authors:       grml-team (grml.org), (c) Michael Prokop <mika@grml.org>
# Bug-Reports:   see https://grml.org/bugs/
# License:       This file is licensed under the GPL v2 or any later version.
################################################################################

set -u
set -e

if ! [ -x $target/sbin/depmod ] ; then
  echo "Warning: depmod not installed"
  exit 0
fi

for kernel in ${target}/boot/vmlinuz-* ; do
  kernelversion=${kernel##$target}
  kernelversion=${kernelversion##/boot/vmlinuz-}

  echo "Updating modules.dep for kernel $kernelversion"
  $ROOTCMD depmod -ae -F /boot/System.map-"$kernelversion" "$kernelversion"
done

## END OF FILE #################################################################
# vim:ft=sh expandtab ai tw=80 tabstop=4 shiftwidth=2
