#!/bin/sh
# Filename:      /etc/grml/fai/config/scripts/GRMLBASE/21-usersetup
# Purpose:       adjust user setup of the live-system
# Authors:       grml-team (grml.org), (c) Michael Prokop <mika@grml.org>
# Bug-Reports:   see http://grml.org/bugs/
# License:       This file is licensed under the GPL v2 or any later version.
# Latest change: Wed Sep 19 20:27:03 CEST 2007 [mika]
################################################################################

set -u
set -e

USERNAME=''
[ -r /etc/grml/grml-live.conf ] && . /etc/grml/grml-live.conf
[ -n "$USERNAME" ] || USERNAME=grml

if grep -q "$USERNAME:x:1000" $target/etc/group ; then
   echo "group $USERNAME exists already, skipping"
else
  $ROOTCMD addgroup --gid 1000 $USERNAME
fi

if grep -q "$USERNAME:x:1000" $target/etc/passwd ; then
   echo "user $USERNAME exists already, skipping"
else
   $ROOTCMD useradd -d /home/$USERNAME -m -s /bin/zsh -g 1000 $USERNAME
fi

sed -i 's/^root::/root:*:/'            $target/etc/shadow
sed -i "s/^$USERNAME:!:/$USERNAME:*:/" $target/etc/shadow

$ROOTCMD chsh -s /bin/zsh root
$ROOTCMD chsh -s /bin/zsh $USERNAME

## END OF FILE #################################################################
# vim:ft=sh expandtab ai tw=80 tabstop=4 shiftwidth=3
