#!/bin/sh
# Filename:      /etc/grml/fai/config/scripts/GRMLBASE/25-locales
# Purpose:       locales (language) configuration of the live system
# Authors:       grml-team (grml.org), (c) Michael Prokop <mika@grml.org>
# Bug-Reports:   see http://grml.org/bugs/
# License:       This file is licensed under the GPL v2 or any later version.
################################################################################

set -e

if [ -z "$ROOTCMD" ] ; then
   echo "variable \$ROOTCMD not set, exiting to avoid any possible damage">&2
   exit 1
fi

# use full locales setup only in classes GRML_FULL and LOCALES
if ifclass GRML_FULL || ifclass LOCALES ; then
   echo 'Using /etc/locale.gen.grml for locales generation'
   cp $target/etc/locale.gen.grml $target/etc/locale.gen
else
   echo 'Using /etc/locale.gen.minimal for locales generation'
   cp $target/etc/locale.gen.minimal $target/etc/locale.gen
fi

# make sure:
# localepurge     localepurge/nopurge     multiselect ....
# is set so localepurge works as expected
if [ -x $target/usr/sbin/localepurge ] ; then
   $ROOTCMD dpkg-reconfigure -f noninteractive localepurge
fi

if [ -x $target/usr/sbin/locale-gen ] ; then
   $ROOTCMD locale-gen
else
   echo 'Warning: locale-gen [package locales] not available'
fi

if [ -x $target/usr/sbin/localepurge ] ; then
   $ROOTCMD localepurge
fi

# get rid of LC_MESSAGES unless using class LOCALES
if ! ifclass LOCALES ; then
   echo 'Removing /usr/share/locale'
   $ROOTCMD rm -rf /usr/share/locale
   $ROOTCMD mkdir /usr/share/locale
   # TODO: /usr/share/i18n/locales
fi

## END OF FILE #################################################################
# vim:ft=sh expandtab ai tw=80 tabstop=4 shiftwidth=3
