#!/bin/sh
# Filename:      /etc/grml/fai/config/scripts/GRML/30-fstab
# Purpose:       create initial /etc/fstab for use on live-system
# Authors:       grml-team (grml.org), (c) Michael Prokop <mika@grml.org>
# Bug-Reports:   see http://grml.org/bugs/
# License:       This file is licensed under the GPL v2 or any later version.
# Latest change: Sun Sep 16 23:09:08 CEST 2007 [mika]
################################################################################

set -u
set -e

USERNAME=''
[ -r /etc/grml/grml-live.conf ] && . /etc/grml/grml-live.conf
[ -n "$USERNAME" ] || USERNAME=grml

if [ -r /etc/grml/fai/files/etc/fstab ] ; then
   cp /etc/grml/fai/files/etc/fstab $target/etc/fstab
   sed -i "s/uid=USERNAME,gid=USERNAME/uid=$USERNAME,gid=$USERNAME/" $target/etc/fstab
fi

## END OF FILE #################################################################
# vim:ft=sh expandtab ai tw=80 tabstop=4 shiftwidth=3
