#!/bin/sh
# Filename:      /etc/grml/fai/config/scripts/GRMLBASE/32-xorg
# Purpose:       make sure there does not exist /etc/X11/xorg.conf by default
# Authors:       grml-team (grml.org), (c) Michael Prokop <mika@grml.org>
# Bug-Reports:   see http://grml.org/bugs/
# License:       This file is licensed under the GPL v2 or any later version.
# Latest change: Sun Sep 16 23:17:08 CEST 2007 [mika]
################################################################################

set -u
set -e

if [ -r "$target/etc/X11/xorg.conf" ] ; then
   mv -f "$target"/etc/X11/xorg.conf "$target"/etc/X11/xorg.conf.debian
fi

## END OF FILE #################################################################
# vim:ft=sh expandtab ai tw=80 tabstop=4 shiftwidth=3
