#!/bin/sh
# Filename:      /etc/grml/fai/config/scripts/GRMLBASE/33-aptsetup
# Purpose:       configure Debian package management of live-system
# Authors:       grml-team (grml.org), (c) Michael Prokop <mika@grml.org>
# Bug-Reports:   see http://grml.org/bugs/
# License:       This file is licensed under the GPL v2 or any later version.
################################################################################

set -u
set -e

rm -f $target/etc/apt/sources.list

$ROOTCMD ln -s /etc/apt/sources.list.grml /etc/apt/sources.list

# if we have a devel-version or a daily snapshot
# let's activate grml-testing by default:
if [ -n "$GRML_NAME" -o -n "$RELEASENAME" ] ; then
   if echo "$GRML_NAME" "$RELEASENAME" | grep -e devel -e autobuild 1>/dev/null ; then
      sed -i 's|^#\(.*deb.*deb.grml.org.*grml-testing\)|\1|' "$target"/etc/apt/sources.list
   fi
fi

#if [ -r /etc/grml/fai/files/etc/apt/preferences ] ; then
#   cp /etc/grml/fai/files/etc/apt/preferences $target/etc/apt/preferences
#fi

## END OF FILE #################################################################
# vim:ft=sh expandtab ai tw=80 tabstop=4 shiftwidth=3
