#!/bin/sh
# Filename:      /etc/grml/fai/config/scripts/GRMLBASE/34-hosts
# Purpose:       configure /etc/hosts of live-system
# Authors:       grml-team (grml.org), (c) Michael Prokop <mika@grml.org>
# Bug-Reports:   see http://grml.org/bugs/
# License:       This file is licensed under the GPL v2 or any later version.
# Latest change: Sat Oct 06 12:35:30 CEST 2007 [mika]
################################################################################

set -u
set -e

HOSTNAME=''
[ -r /etc/grml/grml-live.conf ]  && . /etc/grml/grml-live.conf
[ -r /etc/grml/grml-live.local ] && . /etc/grml/grml-live.local
[ -n "$HOSTNAME" ] || HOSTNAME=grml

if [ -r /etc/grml/fai/files/etc/hosts ] ; then
   cp /etc/grml/fai/files/etc/hosts $target/etc/hosts
fi

# replace $HOSTNAME with the real hostname:
sed -i "s/\$HOSTNAME/$HOSTNAME/" $target/etc/hosts

## END OF FILE #################################################################
# vim:ft=sh expandtab ai tw=80 tabstop=4 shiftwidth=3
