#!/bin/bash
# Filename:      ${GRML_FAI_CONFIG}/config/scripts/GRMLBASE/37-portmap
# Purpose:       configure portmap of live-system
# Authors:       grml-team (grml.org), (c) Michael Prokop <mika@grml.org>
# Bug-Reports:   see https://grml.org/bugs/
# License:       This file is licensed under the GPL v2 or any later version.
################################################################################

set -u
set -e

# Work around a bug in the portmap package, see
# http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=317358

CONFFILE="$target/etc/default/portmap"

# modify only if the file is present, nowadays we have rpcbind
if [ -r "$CONFFILE" ] ; then
 # modify it iff we have portmap's default configuration
 if grep -q '^OPTIONS="-i 127.0.0.1"' "$CONFFILE" ; then
   # disable the "-i 127.0.0.1" configuration so it works e.g. with
   # grml-terminalserver OOTB:
   printf "Removing loopback-interface-only option (workaround #317358) in /etc/default/portmap: "
   sed -i 's/^OPTIONS.*/# OPTIONS="-i 127.0.0.1"/' "$CONFFILE" && echo OK || echo ERROR
 fi
fi

## END OF FILE #################################################################
# vim:ft=sh expandtab ai tw=80 tabstop=4 shiftwidth=2
