#!/bin/bash
# Filename:      ${GRML_FAI_CONFIG}/config/scripts/GRMLBASE/42-branding
# Purpose:       install branding files
# Authors:       grml-team (grml.org), (c) Michael Prokop <mika@grml.org>
# Bug-Reports:   see http://grml.org/bugs/
# License:       This file is licensed under the GPL v2 or any later version.
################################################################################

set -u
set -e

fcopy -v /usr/share/initramfs-tools/scripts/init-top/grml
fcopy -v /usr/share/grml/desktop-bg.png
fcopy -v /usr/share/doc/grml-docs/startpage.html

## END OF FILE #################################################################
# vim:ft=sh expandtab ai tw=80 tabstop=4 shiftwidth=2
