#!/bin/sh
# Filename:      ${GRML_FAI_CONFIG}/config/scripts/GRMLBASE/47-update-wallpaper
# Purpose:       Update the grml wallpaper
# Authors:       grml-team (grml.org)
# Bug-Reports:   see https://grml.org/bugs/
# License:       This file is licensed under the GPL v2 or any later version.
################################################################################

. "$GRML_LIVE_CONFIG"

FONTFILE=${FONTFILE:-/usr/share/grml-live/fonts/graphicoreBitmapFont0-Light.otf}
TITLE_FONTSIZE=${TITLE_FONTSIZE:-200}
VERSION_FONTSIZE=${VERSION_FONTSIZE:-100}
GRML_BG=${GRML_BG:-$target/usr/share/grml/desktop-bg.png}
GRML_WALLPAPER=${GRML_WALLPAPER:-$target/usr/share/grml/desktop.jpg}

if [ ! -x "$(which convert)" ]; then
  echo "convert not installed, skipping wallpaper."
  exit 0
fi

if [ ! -f "$GRML_BG" ]; then
    echo "Could not find Grml background image, skipping wallpaper"
    exit 0
fi

if [ ! -f "$FONTFILE" ]; then
    echo "Could not find font $FONTFILE, skipping wallpaper"
    exit 0
fi

echo "Creating standard wallpaper"

convert "$GRML_BG" -gravity center \
    -fill white -font "$FONTFILE" \
    -pointsize $TITLE_FONTSIZE \
    -draw "text 0,0 \"$GRML_NAME\"" \
    -pointsize $VERSION_FONTSIZE \
    -draw "text 0,$((TITLE_FONTSIZE+50)) \"$VERSION\"" "$GRML_WALLPAPER"
