#!/bin/bash
# Filename:      ${GRML_FAI_CONFIG}/config/scripts/GRMLBASE/48-tmpfs
# Purpose:       configure cpufrequtils of live-system
# Authors:       grml-team (grml.org), (c)
# Bug-Reports:   see http://grml.org/bugs/
# License:       This file is licensed under the GPL v2 or any later version.
################################################################################

set -u
set -e

sed -i 's/^RAMTMP=.*/RAMTMP=no/' $target/etc/default/rcS
## END OF FILE #################################################################
# vim:ft=sh expandtab ai tw=80 tabstop=4 shiftwidth=2
