#!/bin/bash
# Filename:      ${GRML_FAI_CONFIG}/config/scripts/GRMLBASE/50-lvm
# Purpose:       adjust LVM configuration
# Authors:       grml-team (grml.org), (c) Michael Prokop <mika@grml.org>
# Bug-Reports:   see http://grml.org/bugs/
# License:       This file is licensed under the GPL v2 or any later version.
################################################################################

set -u
set -e

if ! [ -r "${target}/lib/udev/rules.d/69-lvm-metad.rules" ] ; then
  echo "File /lib/udev/rules.d/69-lvm-metad.rules doesn't exist, skipping execution of script."
  exit 0
fi

echo "Removing /lib/udev/rules.d/69-lvm-metad.rules to avoid automatic LVM scanning"
rm -f "${target}/lib/udev/rules.d/69-lvm-metad.rules"

## END OF FILE #################################################################
# vim:ft=sh expandtab ai tw=80 tabstop=4 shiftwidth=2
