#!/bin/bash
# Filename:      ${GRML_FAI_CONFIG}/config/scripts/GRMLBASE/55-aoetools
# Purpose:       adjust aoetools configuration
# Authors:       grml-team (grml.org), (c) Michael Prokop <mika@grml.org>
# Bug-Reports:   see http://grml.org/bugs/
# License:       This file is licensed under the GPL v2 or any later version.
################################################################################

set -eu

# see https://github.com/grml/grml/issues/32
echo "Removing /usr/lib/modules-load.d/aoetools.conf to avoid automatic aoe discovery"
rm -f "${target}/usr/lib/modules-load.d/aoetools.conf"

# see https://github.com/grml/grml/issues/47
echo "Removing /etc/network/if-up.d/aoe-discover to avoid network startup failures"
rm -f "${target}/etc/network/if-up.d/aoe-discover"

## END OF FILE #################################################################
# vim:ft=sh expandtab ai tw=80 tabstop=4 shiftwidth=2
