#!/bin/sh
# Filename:      /etc/grml/fai/config/scripts/GRML/90-update-alternatives
# Purpose:       set up /etc/alternatives/* according to grml preferences
# Authors:       grml-team (grml.org), (c) Michael Prokop <mika@grml.org>
# Bug-Reports:   see http://grml.org/bugs/
# License:       This file is licensed under the GPL v2 or any later version.
# Latest change: Sun Sep 16 23:02:53 CEST 2007 [mika]
################################################################################

set -u
set -e

if [ -r $target/usr/bin/vim.basic ] ; then
   $ROOTCMD update-alternatives --set editor /usr/bin/vim.basic
fi

if [ -r $target/usr/bin/xterm ] ; then
   $ROOTCMD update-alternatives --set x-terminal-emulator /usr/bin/xterm
fi

if [ -r $target/etc/X11/cursors/whiteglass.theme ] ; then
   $ROOTCMD update-alternatives --set x-cursor-theme /etc/X11/cursors/whiteglass.theme
fi

## END OF FILE #################################################################
# vim:ft=sh expandtab ai tw=80 tabstop=4 shiftwidth=3
