#!/bin/bash
# Filename:      ${GRML_FAI_CONFIG}/config/scripts/GRMLBASE/95-package-information
# Purpose:       store package information of chroot system
# Authors:       grml-team (grml.org), (c) Michael Prokop <mika@grml.org>
# Bug-Reports:   see http://grml.org/bugs/
# License:       This file is licensed under the GPL v2 or any later version.
################################################################################

set -u
set -e

HOSTNAME=''
[ -r /etc/grml/grml-live.conf ]  && . /etc/grml/grml-live.conf
[ -n "$GRML_LIVE_LOCAL_CONFIG" ] && . "$GRML_LIVE_LOCAL_CONFIG"
[ -n "$HOSTNAME" ] || HOSTNAME=grml
PACKAGE_LOG=/var/log/fai/"$HOSTNAME"/last/

if ! [ -w "$PACKAGE_LOG" ] ; then
   echo "Error: can not write to ${PACKAGE_LOG}. Exiting.">&2
   exit 1
else
   # store package list for the build process logs as well:
   COLUMNS=200 $ROOTCMD dpkg --list > "${PACKAGE_LOG}"/dpkg.list
   COLUMNS=200 $ROOTCMD dpkg --get-selections > "${PACKAGE_LOG}"/dpkg.selections
   # store list of packages sorted by size:
   if [ -x $target/usr/bin/dpkg-query ] ; then
      $ROOTCMD dpkg-query -W --showformat='${Package}\t${Installed-Size;10}\n' > \
      "${PACKAGE_LOG}"/packages.size
   fi
fi

## END OF FILE #################################################################
# vim:ft=sh expandtab ai tw=80 tabstop=4 shiftwidth=2
