#!/bin/sh
# Filename:      /etc/grml/fai/config/scripts/GRMLBASE/96-apt-listbugs
# Purpose:       retreive list of bugreports of installed packages inside chroot
# Authors:       grml-team (grml.org), (c) Michael Prokop <mika@grml.org>
# Bug-Reports:   see http://grml.org/bugs/
# License:       This file is licensed under the GPL v2 or any later version.
# Latest change: Sun Nov 04 01:42:58 CET 2007 [mika]
################################################################################

set -e

if ifclass RELEASE ; then

  HOSTNAME=''
  [ -r /etc/grml/grml-live.conf ] && . /etc/grml/grml-live.conf
  [ -n "$HOSTNAME" ] || HOSTNAME=grml

  if [ -r /etc/resolv.conf ] ; then
     cat /etc/resolv.conf >> $target/etc/resolv.conf
  fi

  if [ -x $target/usr/sbin/apt-listbugs -a -x $target/usr/bin/apt-show-source ] && \
     [ -x $target/etc/apt/grml/listbugs ] ; then
     for severity in critical grave serious ; do
         SEVERITY=$severity $ROOTCMD /etc/apt/grml/listbugs > \
         /var/log/fai/dirinstall/$HOSTNAME/bugs.${severity} || true # make sure it does not fail
     done
  fi

fi

## END OF FILE #################################################################
