#!/bin/sh
# Filename:      /etc/grml/fai/config/scripts/GRMLBASE/96-apt-listbugs
# Purpose:       retreive list of bugreports of installed packages inside chroot
# Authors:       grml-team (grml.org), (c) Michael Prokop <mika@grml.org>
# Bug-Reports:   see http://grml.org/bugs/
# License:       This file is licensed under the GPL v2 or any later version.
# Latest change: Sun Nov 04 22:40:43 CET 2007 [mika]
################################################################################

set -e

# Defaults:
#apt-listchanges apt-listchanges/confirm boolean false
#apt-listchanges apt-listchanges/email-address   string  root
#apt-listchanges apt-listchanges/which   select  news
#apt-listchanges apt-listchanges/frontend        select  pager
#apt-listchanges apt-listchanges/save-seen       boolean true
if [ -x $target/usr/bin/apt-listchanges ] ; then
   echo 'apt-listchanges apt-listchanges/confirm boolean true' | $ROOTCMD debconf-set-selections
   echo 'apt-listchanges apt-listchanges/which   select  both' | $ROOTCMD debconf-set-selections
fi

if [ -r $target/etc/apt/apt.conf.d/10apt-listbugs ] ; then
   sed -i 's#//DPkg::#DPkg::#' $target/etc/apt/apt.conf.d/10apt-listbugs
fi

if ifclass RELEASE ; then

  HOSTNAME=''
  [ -r /etc/grml/grml-live.conf ] && . /etc/grml/grml-live.conf
  [ -n "$HOSTNAME" ] || HOSTNAME=grml

  if [ -r /etc/resolv.conf ] ; then
     if [ -r $target/etc/resolvconf/run/resolv.conf ] ; then
        cat /etc/resolv.conf >> $target/etc/resolvconf/run/resolv.conf
     else
        cat /etc/resolv.conf >> $target/etc/resolv.conf
     fi
  fi

  if [ -x $target/usr/sbin/apt-listbugs -a -x $target/usr/bin/apt-show-source ] && \
     [ -x $target/etc/apt/grml/listbugs ] ; then
     for severity in critical grave serious ; do
         SEVERITY=$severity $ROOTCMD /etc/apt/grml/listbugs > \
         /var/log/fai/dirinstall/$HOSTNAME/bugs.${severity} || true # make sure it does not fail
     done
  fi

fi

## END OF FILE #################################################################
