#!/bin/sh
# Filename:      /etc/grml/fai/config/scripts/GRMLBASE/99-finish-grml-build
# Purpose:       finalize grml chroot build
# Authors:       grml-team (grml.org), (c) Michael Prokop <mika@grml.org>
# Bug-Reports:   see http://grml.org/bugs/
# License:       This file is licensed under the GPL v2 or any later version.
# Latest change: Sun Nov 04 22:28:54 CET 2007 [mika]
################################################################################

set -u
set -e

# Restore usual Debian behaviour which has been changed
# for FAI via /etc/grml/fai/config/hooks/instsoft.GRMLBASE
if [ -r $target/etc/apt/apt.conf ] ; then
   sed -i "s#^Acquire::http::Pipeline-Depth.*#// &#" $target/etc/apt/apt.conf
   sed -i "s#^APT::Install-Recommends.*#// &#"       $target/etc/apt/apt.conf
fi

# Restore original state from softupdate:
if [ -r $target/etc/policy-rc.d.conf ] ; then
   sed -i "s/EXITSTATUS='101'/EXITSTATUS='0'/" $target/etc/policy-rc.d.conf
fi

# remove an existing /etc/debian_chroot file:
if [ -r $target/etc/debian_chroot ] ; then
   rm -f $target/etc/debian_chroot
fi

# /etc/grml_cd makes the live system recognizable as a live system
touch $target/etc/grml_cd

## END OF FILE #################################################################
# vim:ft=sh expandtab ai tw=80 tabstop=4 shiftwidth=3
