#!/bin/sh
# Filename:      /etc/grml/fai/config/scripts/GRMLBASE/99-finish-grml-build
# Purpose:       finalize grml chroot build
# Authors:       grml-team (grml.org), (c) Michael Prokop <mika@grml.org>
# Bug-Reports:   see http://grml.org/bugs/
# License:       This file is licensed under the GPL v2 or any later version.
# Latest change: Sun Sep 16 23:04:36 CEST 2007 [mika]
################################################################################

set -u
set -e

# /etc/grml_cd makes the live system recognizable as a live system
touch $target/etc/grml_cd

## END OF FILE #################################################################
# vim:ft=sh expandtab ai tw=80 tabstop=4 shiftwidth=3
