#!/bin/sh
# Filename:      /etc/grml/fai/config/scripts/GRMLBASE/99-finish-grml-build
# Purpose:       finalize grml chroot build
# Authors:       grml-team (grml.org), (c) Michael Prokop <mika@grml.org>
# Bug-Reports:   see http://grml.org/bugs/
# License:       This file is licensed under the GPL v2 or any later version.
# Latest change: Mon Oct 15 19:12:13 CEST 2007 [mika]
################################################################################

set -u
set -e

# Restore usual Debian behaviour which has been changed
# for FAI via /etc/grml/fai/config/hooks/instsoft.GRMLBASE
if [ -r $target/etc/apt/apt.conf ] ; then
   sed -i "s#Acquire::http::Pipeline-Depth.*#// &#" $target/etc/apt/apt.conf
fi

# /etc/grml_cd makes the live system recognizable as a live system
touch $target/etc/grml_cd

## END OF FILE #################################################################
# vim:ft=sh expandtab ai tw=80 tabstop=4 shiftwidth=3
