#!/bin/bash
# Filename:      ${GRML_FAI_CONFIG}/config/scripts/GRMLBASE/90-update-alternatives
# Purpose:       set up /etc/alternatives/* according to grml preferences
# Authors:       grml-team (grml.org), (c) Michael Prokop <mika@grml.org>
# Bug-Reports:   see http://grml.org/bugs/
# License:       This file is licensed under the GPL v2 or any later version.
################################################################################

set -u
set -e

## Editor:
# Too many people don't expect to get that, so use it only for grml-small
# avoid "debug: unbound variable":
set +u
if ifclass GRML_SMALL ; then
set -u
   if [ -r $target/usr/bin/vim.tiny ] ; then
      # update-alternates does not work without /usr/share/man because
      # it configures (in our case non-existent) manpages as well :-/
      # $ROOTCMD update-alternatives --set editor /usr/bin/vim.tiny
      # $ROOTCMD update-alternatives --set vi     /usr/bin/vim.tiny
      $ROOTCMD ln -sf /etc/alternatives/editor /usr/bin/editor
      $ROOTCMD ln -sf /usr/bin/vim.tiny /etc/alternatives/editor
      $ROOTCMD ln -sf /etc/alternatives/vi /usr/bin/vi
      $ROOTCMD ln -sf /usr/bin/vim.tiny /etc/alternatives/vi
      $ROOTCMD ln -sf /etc/alternatives/vim /usr/bin/vim
      $ROOTCMD ln -sf /usr/bin/vim.tiny /etc/alternatives/vim
      $ROOTCMD ln -sf /etc/alternatives/view /usr/bin/view
      $ROOTCMD ln -sf /usr/bin/vim.tiny /etc/alternatives/view
   fi
fi
