#!/bin/bash
# Filename:      ${GRML_FAI_CONFIG}/config/scripts/GRML_SMALL/98-clean-chroot
# Purpose:       clean up Grml chroot on grml-small
# Authors:       (c) Michael Prokop <mika@grml.org>
# Bug-Reports:   see http://grml.org/bugs/
# License:       This file is licensed under the GPL v2.
################################################################################

set -e
set -u

echo "Removing /usr/share/ssh/blacklist.*"
rm -f $target/usr/share/ssh/blacklist.DSA-1024 $target/usr/share/ssh/blacklist.RSA-2048

echo "Cleaning documentation directories"
if [ -d $target/usr/share/doc/grml-docs ] ; then
  mv $target/usr/share/doc/grml-docs $target/tmp/
fi

## END OF FILE #################################################################
# vim:ft=sh expandtab ai tw=80 tabstop=4 shiftwidth=2
