grml-live(8)
============

Name
----

grml-live - build framework for the Grml Live Linux system

Synopsis
--------

grml-live --help

grml-live image-create [--boot-options DEFAULT_BOOTOPTIONS] [-c CLASS1,CLASS2]
          [--distri-info DISTRI_INFO] [--distri-name DISTRI_NAME] [--hostname HOSTNAME]
          [--username USERNAME] [-d DATE] [-D CONFIGDIR] [-F] [-g GRML_NAME] [-i ISO_NAME]
          [-I CHROOT_INSTALL_DIRECTORY] [-r RELEASE_NAME] [-R] [-s SUITE] [--secure-boot]
          [-v VERSION_NUMBER] [--bootstrap-mirror-url BOOTSTRAP_MIRROR_URL | -w DATE]
          OUTPUT_DIRECTORY

grml-live image-update [--boot-options DEFAULT_BOOTOPTIONS] [-c CLASS1,CLASS2]
          [--distri-info DISTRI_INFO] [--distri-name DISTRI_NAME] [--hostname HOSTNAME]
          [--username USERNAME] [-d DATE] [-D CONFIGDIR] [-F] [-g GRML_NAME] [-i ISO_NAME]
          [-I CHROOT_INSTALL_DIRECTORY] [-r RELEASE_NAME] [-R] [-s SUITE] [--secure-boot]
          [-v VERSION_NUMBER]
          SOURCE_IMAGE OUTPUT_DIRECTORY

Description
-----------

grml-live is the build system for the Grml Live Linux system. You can also
use it to adapt a Grml release to your own needs.

Foundational ideas:

* single command to build a Grml-/Debian-based Linux Live-CD
* class based concept, providing a maximum of flexibility
* support integration of custom hooks, scripts and configuration
* support integration of own Software and/or Kernels using Debian repositories

The build system is based on the class concept of link:http://fai-project.org/[FAI]
(Fully Automatic Installation). While older versions directly used FAI, the
current version of grml-live supports the same class-based configuration concept
but provides its own implementation.

The class-based configuration concept gives you the flexibility to choose the
packages you would like to include on your own Linux Live-CD without having to
deal with all the details of a build process.

CAUTION: grml-live no longer uses FAI. This means you are free to use FAI
separately in any way you like, but also you no longer need to have FAI installed.

[NOTE]
You should have a fast network connection as all the Debian packages will be
downloaded and installed via network. It is strongly recommended to use a local
mirror - if you plan to use grml-live more than once.
See debmirror(1), reprepro(1), apt-cacher-ng(1) and approx(8). A reprepro sample
configuration is available in the source in examples/reprepro/.

Actions
-------

The `image-create` action builds a new Grml Live Linux image from scratch. +
You must pass an **OUTPUT_DIRECTORY**.
The resulting ISO, netboot images and logs will be created there.

The `image-update` action repacks an existing Grml Live Linux image.
This is used to apply changes in the grml-live configuration and/or add additional classes, within limits.
The options `-s`, `--hostname`, `--username` from the initial build must be given with their original values. +
The existing ISO must be given as **SOURCE_IMAGE**.
You must pass an **OUTPUT_DIRECTORY**.
The resulting ISO, netboot images and logs will be created there.


Options
-------

  --boot-options **BOOT_OPTIONS**::

Add given boot options to the default. A useful example is `ssh`, to autostart
the SSH server.

  --bootstrap-mirror-url **BOOTSTRAP_MIRROR_URL**::

Set a custom Debian mirror URL to use for creating the chroot.

  -c **CLASS1,CLASS2**::

Specify which classes are to be used for building the ISO.
By default the class GRML_FULL is assumed.
See <<classes,the 'CLASSES' section in this document>> for
details about available classes.
Multiple classes can be given using commas.
 +
The classes `DEBIAN_<suite>`, `GRMLBASE`, `RELEASE`, `SECURE_BOOT`, and `AMD64`/`ARM64`
(depending on system architecture) are automatically added when necessary,
and must not be specified. The old `I386` class is rejected. +
For example, instead of `GRML_FULL` you could use `GRML_SMALL`. +
Important: all class names should be written in uppercase letters.
Do not use a dash, use an underscore. So do not use "grml_small" but "GRML_SMALL",
do not use "FOO BAR", but "FOO_BAR". Whitespace is rejected.

  -d **DATE**::

Use specified date as build date information on the ISO instead of the default.
The default is the date when grml-live is being executed (retrieved via
executing 'date +%Y-%m-%d'). The information is stored inside the file
/GRML/grml-version on the ISO, /etc/grml_version in the squashfs file and in all
the bootsplash related files. This option is useful if you want to provide an
ISO with release information for a specific date but have to build it in
advance. Usage example: '-d 2009-10-30'

  -D **CONFIGURATION_DIRECTORY**::

The specified directory is used as configuration directory for grml-live.
By default, when running from source (git checkout), `config` from the source
directory is used. When running from an installed package, the default is
`/usr/share/grml-live/config`. +
If you want to have different configuration scripts, package definitions, etc.
without messing with the global configuration under /usr/share/grml-live/config
provided by grml-live this option provides you the option to use your own
configuration directory. +
This directory is what's being referred to as `$GRML_FAI_CONFIG` throughout this
documentation.

  --distri-info **DISTRI_INFO**::

Set the `DISTRI_INFO` variable. A one-line string describing the operating system
being built.

  --distri-name **DISTRI_NAME**::

Set the `DISTRI_NAME` variable.

  -F::

Force execution and do not prompt for acknowledgment of configuration.

  -g **GRML_NAME**::

Set the grml flavour name. Common usage examples: grml, grml-small, grml64.
Please do NOT use blanks and any special characters like '/', ';' inside
GRML_NAME, otherwise you might notice problems while booting.

  -h::

Display short usage information and exit.

  --hostname **HOSTNAME**::

Set the default hostname of the booted Live ISO.

  -i **ISO_NAME**::

Specify name of ISO which will be available inside $OUTPUT_DIRECTORY/grml_isos.

  -I **CHROOT_INSTALL_DIRECTORY**::

Specify name of source directory which provides files that should become part of
the chroot/ISO. Not enabled by default. Note: the files are installed under '/'
in the chroot so you have to create the rootfs structure on your own.

  -r **RELEASENAME**::

Specify name of the release.

  -R::

After building the chroot, do not clean up for a release ISO. This skips applying
the class "RELEASE".

  -s **SUITE**::

Specify the Debian suite you want to use for your live-system. If unset defaults
to "testing". Supported values are: stable, testing, unstable (or their
corresponding release names like "trixie").

  --secure-boot::

Enable setup of Secure Boot for the built ISO.

  --username **USERNAME**::

Set the name of the created non-root user.

  -v **VERSION_NUMBER**::

Specify version number of the release.

  -w **DATE**::

The wayback machine. Build the system using Debian archives from the specified
date.  Valid date formats are yyyymmddThhmmssZ or simply yyyymmdd.  To learn
which snapshots exist, i.e. which date strings are valid, simply browse the
lists on http://snapshot.debian.org/.  If there is no import at the exact time
you specified you will get the latest available timestamp which is before the
time you specified. +
This option is useful especially for release and debugging builds - for example
if you know that the Debian archive was in a good state on a specific date but
you want to build it on another day in the future, where the archive might not
be as needed anymore. Please be aware that this is restricted to the plain
Debian repositories only, as referred to in /etc/apt/sources.list.d/debian.list
(so neither the Grml repositories nor any further custom ones are affected by
the wayback machine).

Environment variables
---------------------

The variables `APT_PROXY` and `SOURCE_DATE_EPOCH` are honored.

In the past many configuration options could also be passed as environment variables
or configuration file variables, but this support was removed.
Please use the command line options.


[[usage-examples]]
Usage examples
--------------

To get a Grml-based Live-CD based on Debian testing, created in `./my-grml` as output directory just run:

  $ grml-live ./my-grml

To get a 64bit Debian-testing and grml-small based Live-CD using /srv/grml-live
as build and output directory use the following command line on your amd64
system:

  $ grml-live -s testing -c GRML_SMALL /srv/grml-live

The default build directory is in your `TMPDIR`.
To place the temporary files, which can become rather large, into another directory:

  $ mkdir grml-tmp
  $ chmod 0755 grml-tmp
  $ export TMPDIR=$PWD/grml-tmp
  $ grml-live ./my-grml

[NOTE]

If you have enough RAM, just run "mount -t tmpfs none /media/ramdisk" to get a
tmpfs ("RAMDISK"), and use /media/ramdisk as build and output directory - this
results in a very fast build process. Note that these files will be gone when
rebooting.

[[class-concept]]
The class concept
-----------------

grml-live uses a class based concept, like FAI, for adjusting configuration and
customizing the installation according to your needs. This gives you flexibility
and strength without losing the simplicity in the build process.

The main and base class provided by grml-live is named GRMLBASE. grml-live will
automatically add it, together with the architecture-dependent class (being
`AMD64` for x86_64 and `ARM64` for arm64).
The GRML_SMALL and GRML_FULL classes define the official ISO builds.

The following files and directories are relevant for class GRMLBASE by default:

  ${GRML_FAI_CONFIG}/env/GRMLBASE
  ${GRML_FAI_CONFIG}/hooks/updatebase.GRMLBASE
  ${GRML_FAI_CONFIG}/debconf/GRMLBASE
  ${GRML_FAI_CONFIG}/hooks/instsoft.GRMLBASE
  ${GRML_FAI_CONFIG}/package_config/GRMLBASE
  ${GRML_FAI_CONFIG}/scripts/GRMLBASE/
  ${GRML_FAI_CONFIG}/media-scripts/GRMLBASE/

See <<files,Files>> for details about these files and directories.

If you want to use your own configuration, extend an existing configuration
and/or add additional packages to your ISO just invent a new class (or extend an
existing one). For example if you want to use your own class named "FOOBAR" on
your amd64 build, invoke grml-live using the classes option:
`grml-live -c GRML_SMALL,FOOBAR -D /path/to/config ...`.

More details regarding the class concept can be found in the documentation of
FAI (installed by the `fai-doc` Debian package in /usr/share/doc/fai-doc/).
Examples can be found in /usr/share/doc/fai-doc/examples/simple/ .
In the past, grml-live directly used FAI. Nowadays, it uses an internal
implementation of the class concept - not all FAI features are necessarily
available.


[[X7]]
[[classes]]
Available classes
-----------------

The package selection part of the classes can be found in
${GRML_FAI_CONFIG}/package_config whereas some further classes are defined for
example in ${GRML_FAI_CONFIG}/scripts/ so specific feature sets can be
selected. The following classes are predefined:

* `DEBIAN_<suite>`: these classes manage the Debian keyring and
Debian-version-specific packages, like the DHCP client. They are automatically
added by grml-live.

* `DEBORPHAN`: purge autoremove-able and "removed-but-not-yet-purged" packages.
While deborphan itself is not available anymore, the name of the class was kept
for backwards compatibility reasons.

* `FRESHCLAM`: include clamav packages and execute freshclam to get a current
clamav database

* `GRMLBASE`: the main class responsible for getting a minimal subset of what's
defining a Grml system. Important parts of the buildprocess are specified in
this class as well, so unless you have a really good reason you should always
use this class. Please be aware that using *just* the GRMLBASE class won't be
enough, because the kernel packages (e.g. linux-image-pass:[*]) are chosen in
further GRML_pass:[*] classes (to provide maximum flexibility with kernel
selection). If you don't want to use the existing GRML_FULL or GRML_SMALL
classes, define your own CLASS file choosing the kernel package you want to use
(and don't forget to include your CLASS in the arguments of grml-live's `-c...`
command line option).

* `GRML_FULL`: fully featured Grml, also known as the "normal", full grml as
introduced in December 2011 (~1GB ISO size).

* `GRML_SMALL`: minimum sized Grml version, known as grml-small (~600MB ISO
size).

* `LATEX`: LaTeX(-related) packages like auctex, texlive,...
(which used to be shipped by grml before the LaTeX removal)

* `LATEX_CLEANUP`: get rid of several very large LaTeX directories
(like some /usr/share/doc/texlive-*, /usr/share/doc/texmf,...)

* `LOCALES`: use full featured locales setup (see /etc/locale.gen.grml). This
avoids to get rid of /usr/share/locale - which happens by default otherwise - as
well.

* `NO_ONLINE`: do not run scripts during the chroot build process which require a
network connection

* `RELEASE`: run some specific scripts and commands to provide the workflow for an
official grml release

* `REMOVE_DOCS`: get rid of documentation directories (like /usr/share/doc,
/usr/share/man/, /usr/share/info,...)

* `SECURE_BOOT`: internal class to control secure boot setup.
Automatically added with the `--secure-boot` option.

* `SOURCES`: retrieve Debian source packages after installation. Files will be
placed in the output directory under grml_sources.

* `TOR`: generates a Tor onion service at build time. This makes the
  booted system available even if behind NAT or some firewall that is
  broken or unknown, and you need to get a rescue shell on the
  host. Note that the Tor private keys are persisted in the ISO, which
  makes the build artifacts contain secret material and should be
  handled accordingly (although the consequence of disclosure is
  simply access to the onion service, which is not necessarily a
  problem).
  The option `--boot-options=ssh` should also be added to the grml-live invocation to ensure SSH starts.
  The `netconfig=` and/or `encpasswd=...` boot options should
  also be used to tell GRML to download SSH keys or set a known
  password, or use the `-I` parameters to inject
  those public keys directly at build time.

* `XORG`: providing important packages for use with a base grml-featured X.org
setup

* `ZFS`: package selection to add support for OpenZFS/zfsonlinux

[[files]]
Files
-----

Overview of all files relevant to grml-live and the config area.

  /usr/sbin/grml-live

Main program driving the build process.

  ${GRML_FAI_CONFIG}/

The <<grml_fai_config_variable,main directory>> for configuration of grml-live.
To change this, pass `-D` to grml-live.
More details on individual files below.
Each subdirectory will have files or directories per "class". You can pick
a single or multiple classes when invoking grml-live. Only the classes you
selected (plus automatic classes) will influence the build result.
Most customizations can be applied by defining a new class for your own use.

  ${GRML_FAI_CONFIG}/env/

This directory contains files specifying environment variables for each
class. The content of all (selected) files is merged.

  ${GRML_FAI_CONFIG}/debconf/

This directory provides the files for preseeding/configuration of debconf
through files.

  ${GRML_FAI_CONFIG}/hooks/

This directory provides files for customising the build process through hooks.
Hooks are user defined programs or scripts, which are called during the
installation process.

  ${GRML_FAI_CONFIG}/package_config/

Directory with lists of software packages to be installed or removed. Please
note that GRMLBASE contains a package list defining a minimum but still
reasonable package configuration.

  ${GRML_FAI_CONFIG}/scripts/

Scripts customising the chroot (the future squashfs contents) during the
build process.

  ${GRML_FAI_CONFIG}/media-scripts/

Scripts customising the ISO contents during the build process. The squashfs
will not be available when these scripts run.

  ${GRML_FAI_CONFIG}/tools/

Tools available in PATH when scripts and media-scripts are run. Later classes
overwrite tools from earlier classes, if they share names.

[[log-files]]
Available log files
-------------------

Log files are written into a directory named `grml_logs` in the output directory
- next to `grml_isos`, etc.

Versions before 0.17.0 used to log into `/var/log/grml-live.log` and
`/var/log/fai/grml` instead.


[[requirements]]
Requirements for the build system
---------------------------------

* Debian GNU/Linux 13 ("trixie") or newer. If this doesn't work, please send us
a bug report. Check out <<deploy-on-debian,How do I deploy
grml-live on a plain Debian installation>> for details how to set up grml-live
on a plain, original Debian system.

* Linux user namespaces must work, and the executing user needs subuid and subgid
ranges assigned. See the manual pages subuid(5) and subgid(5).

* enough free disk space. At least 2GB are required for a minimal grml-live
run (\~1GB for the chroot, \~400MB for the build target, \~35MB for the netboot
files and \~350MB for the resulting ISO plus some temporary files).
If you plan to build GRML_FULL you should have at least 4GB of total free disk
space.

* fast network access for retrieving the Debian packages used for creating the
chroot (check out "local mirror" to workaround this problem as far as possible)

* your output directory must not be mounted with any of the "nodev", "noexec"
or "nosuid" mount options. (/tmp typically is at least "nodev" and "nosuid" on
most systems.)

For further information see next section.

[[faq]]
FAQ
---

[[deploy-on-debian]]
How do I deploy grml-live on a plain Debian installation?
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

grml-live runs on a plain <<requirements,Debian installation>>.
It is recommended to <<run-from-git,run from source>>.

What we have: plain, original Debian trixie (13).

What we want: build a Grml ISO based on Debian/trixie for the amd64
architecture using grml-live.

Install git and clone grml-live:

  $ apt install git
  $ git clone --depth 1 https://github.com/grml/grml-live
  $ cd grml-live

Make a branch for your customizations:

  $ git switch -c mywork

Invoke the ISO build process:

  $ ./grml-live -c GRML_FULL

This will take a while to download the Debian packages, install them and build
the final ISO. If everything worked as expected the last line of the
shell output should look like:

  [*] Successfully finished execution of grml-live [running 687 seconds]

The resulting ISO can then be found in `./grml/grml_isos/`.

[[grml_fai_config_variable]]
What is $GRML_FAI_CONFIG?
~~~~~~~~~~~~~~~~~~~~~~~~~

This documentation uses `$GRML_FAI_CONFIG` to mean where grml-live looks
for the configuration directory, which defines what ends up being part of
your Grml build. See the section <<class-concept,The class concept>> for details.

By default, it points to the configuration shipped with
grml-live. If you are running grml-live from a source (git) checkout,
it defaults to using the `config` directory from that checkout.
If you are running grml-live from an installed package, it defaults to
`/usr/share/grml-live/config`.

To change `$GRML_FAI_CONFIG`, pass `-D <config_dir>` to grml-live.
Now `$GRML_FAI_CONFIG` points to the specified directory and all the
configuration files, scripts and hooks will be taken from your
`$GRML_FAI_CONFIG` directory.
This allows for a maximum of flexibility.

We encourage you to fork grml-live.git and apply your changes to the `config`
directory as git commits.


[[how-to-debug]]
I've problems with the build process. How to start debugging?
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Check out the logs inside the directory `grml_logs` in the output directory.

If you need help with grml-live or would like to see new features as part of
grml-live you can get commercial support via
link:http://grml-solutions.com/[Grml Solutions].

If there were errors during the build, grml-live should have aborted when
the error happened.

[[install-local-files]]
How do I install further files into the chroot/ISO?
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Just point the `-I` parameter to the directory which
provides the files you would like to install. Note that the files are installed
under '/' in the chroot - so you have to create the rootfs structure on your
own. Usage example:

  mkdir -p chroot_install/etc
  echo 'this is a motd' > chroot_install/etc/motd
  grml-live -I chroot_install ...

[[local-debian-mirror]]
Can I use my own (local) Debian mirror?
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Yes. Set up an according sources.list configuration as class file in
${GRML_FAI_CONFIG}/files/${CLASS}/etc/apt/sources.list.d/ and pass
`--bootstrap-mirror-url` to grml-live. If you're setting up
your own class file make sure to include the class name in the class list
(grml-live -c ...).

If you want to use a HTTP Proxy (like apt-cacher-ng), set APT_PROXY. Example:

  APT_PROXY="http://localhost:3142/"

[[add-additional-debian-packages]]
How do I add additional Debian package(s) to my CD/ISO?
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Define a new class. In this example we will use the name "MIKA".
Create the `package_config` file for the class:

  # cat > $GRML_FAI_CONFIG/package_config/MIKA << EOF
  PACKAGES install

  vim
  another_name_of_a_debian_package
  and_another_one
  EOF

And pass it as an **additional** class to grml-live:

  $ grml-live -c GRML_SMALL,MIKA ./my-grml

[[reset-grml-live-configuration]]
I fscked up my grml-live configuration. How do I reset it to the defaults?
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

If you make changes to the grml-live configuration files, it is recommended
you copy them to a new directory, modify them there and pass `-D` to grml-live.

If you modified them inside /usr/share/grml-live, you can just reinstall
grml-live:

  # apt remove grml-live
  # apt install grml-live

Note: modified files in /usr/share/grml-live will not survive upgrades of
grml-live.

[[apt-cacher]]
Set up apt-cacher-ng for use with grml-live
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Make sure apt-cacher-ng is running ('/etc/init.d/apt-cacher-ng restart').
Then set the `APT_PROXY` environment variable before running grml-live:

  export APT_PROXY="http://localhost:3142/"
  grml-live ...

That's it.  All downloaded files will be cached in /var/cache/apt-cacher-ng then.

[[create-a-base-tgz]]
How do I create a base tar.gz (AMD64.tar.gz or ARM64.tar.gz)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[[basetgz]]

This is no longer supported. grml-live will call mmdebstrap for you.

[[localrepos]]
How to use your own local repository
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Let's assume you have Debian package(s) in your filesystem inside
`/home/foobar/local-packages` and want to provide them to your grml-live build.
The easiest option is by serving this repository via HTTP.

Serving a repository via HTTP
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Make sure to create an according sources.list configuration file, e.g. using
your own class name `CUSTOM`:

  # cat > $GRML_FAI_CONFIG/files/CUSTOM/etc/apt/sources.list.d/local-packages.list << EOF
  deb http://127.0.0.1:8000/ ./
  EOF

Make sure the local directory is served via HTTP on the according IP address and
port. For the `http://127.0.0.1:8000/` example from above it should be enough to
just invoke:

  % cd /home/foobar/packages
  % dpkg-scanpackages . /dev/null | gzip > Packages.gz
  % python -m http.server 8000

[TIP]
Of course you can also use a real Debian repository setup using tools like
reprepro(1) and/or using a real web server, though for quick debugging sessions
python's link:https://docs.python.org/3/library/http.server.html[http.server]
in combination with dpkg-scanpackages from package
dpkg-dev is a simple and easy approach.

Finally invoke grml-live with your class name (`CUSTOM` in this example) added
to the list of classes on the command line (see grml-live option `-c`).

[[userns]]
Error: `unshare: no line matching ... in /etc/subuid`
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

grml-live uses Linux user namespaces, instead of running everything as root on
your host system. This requires that your user has "subuid" and "subgid" ranges
assigned. See the manual pages subuid(5), subgid(5) and newuidmap(1).

On Debian systems, when the `uidmap` package is installed, newly created users
automatically get subuid and subgid ranges assigned by useradd(8).


[[run-from-git]]
Obtaining and running grml-live
-------------------------------
[[download]]

The best option for running grml-live is to run it directly from a git
repository checkout. The file `debian/control` lists all required dependencies.

When running from the git checkout, grml-live will automatically use the
configuration space (aka `$GRML_FAI_CONFIG`) from the repository. If you want
another directory, use the `-D` option.

Usage example:

    $ git clone --depth 1 https://github.com/grml/grml-live
    $ cd grml-live
    $ sudo apt install <packages>  # see debian/control
    $ ./grml-live -D "$PWD/config" -s sid -c GRML_FULL ./my-grml


Debian package
~~~~~~~~~~~~~~

If your workflow requires a Debian package of grml-live, you can build one from
the git checkout.

Example:

    $ sudo apt install git sbuild
    $ git clone https://github.com/grml/grml-live
    $ cd grml-live
    $ sbuild


[[source]]
Source
------

The source of grml-live is available at
link:https://github.com/grml/grml-live/[https://github.com/grml/grml-live/]

[[bugs]]
Bugs
----

Please report feedback, link:http://grml.org/bugs/[bugreports] and wishes
link:http://grml.org/contact/[to the Grml team]!

[[documentation]]
Documentation
-------------

The most recent grml-live documentation is available online at
https://grml.org/grml-live/ .

[[authors]]
Authors
-------
Michael Prokop <mika@grml.org>

/////////////////////////////////////
// vim:ai tw=80 ft=asciidoc expandtab
/////////////////////////////////////
