grml-live(8)
============

Name
----

grml-live - build framework for the Grml Live Linux system

Synopsis
--------

grml-live [-a <architecture>] [-c <classe[s]>] [-C <configfile>] [
-e <extract_iso_name>] [-g <grml_name>] [-i <iso_name>] [
-o <output_directory>] [-r <release_name>] [-s <suite>] [
-t <arg>] [-v <version_number>] [-U <username>] [
-w <date>] [-AbBFnNqQRuVz]

Description
-----------

grml-live is the build system for the Grml Live Linux system. You can also
use it to adapt a Grml release to your own needs.

The build system is based on the class concept of link:http://fai-project.org/[FAI]
(Fully Automatic Installation). While older versions directly used FAI, the
current version of grml-live supports the same class-based configuration concept
but provides its own implementation.

The class-based configuration concept gives you the flexibility to choose the
packages you would like to include on your own Linux Live-CD without having to
deal with all the details of a build process.

CAUTION: grml-live no longer uses FAI. This means you are free to use FAI
separately in any way you like, but also you no longer need to have FAI installed.

[NOTE]

Please notice that you should have a fast network connection as all the Debian
packages will be downloaded and installed via network. If you want to use a
local mirror (strongly recommended if you plan to use grml-live more than once)
checkout debmirror(1), reprepro(1) (see /usr/share/doc/grml-live/examples/reprepro/ for a
sample configuration), apt-cacher(1) and approx(8).

Options
-------

  -A::

Clean up all output directories before running the build process. After finishing,
clean up the Chroot target and Build target directories.

  -a **ARCHITECTURE**::

Use the specified architecture instead of the currently running one.  This
allows building a 32bit system on a 64bit host (though you can't build a 64bit
system on a 32bit system/kernel of course). Please notice that real
crosscompiling (like building a ppc system on x86) isn't possible due to the
nature and the need of working in a chroot. Currently supported values: i386,
amd64 and arm64.

  -b::

Build the ISO without updating the chroot. This option is useful for
example when working on stable releases: if you have a working base
system/chroot and do not want to execute any further updates (via "-u" option)
but intend to only build the ISO.

  -B::

Build the ISO without touching the chroot at all. This option is useful if
you modified anything grml-live might adjust via the class-based configuration.
It's like the '-b' option but even more advanced. Use only if you really know
that you do not want to update the chroot.

  -c **CLASSES**::

Specify the CLASSES to be used for building the ISO.  By default only
the class GRML_FULL is assumed.  Additionally you can specify a class providing a
(grml-)kernel (see <<classes,the 'CLASSES' section in this document>> for
details about available classes). So instead of GRML_FULL you can also use e.g.
GRML_SMALL.

The classes GRMLBASE, RELEASE, and AMD64/ARM64 (depending on system
architecture) are automatically added, and shall not be given on the
command line.

[IMPORTANT]
All class names should be written in uppercase letters. Do not use a dash, use
an underscore. So do not use "grml_small" but "GRML_SMALL", do not use "FOO BAR"
but "FOO_BAR".


  -C **CONFIGURATION_FILE**::

The specified file is used as configuration file for grml-live. By default
/etc/grml/grml-live.conf is used as default configuration. If a file named
/etc/grml/grml-live.local exists it is used as well (sourced after reading
/etc/grml/grml-live.conf meant as main file for local configuration). As a last
option the specified configuration file is sourced so it is possible to override
settings of /etc/grml/grml-live.conf as well as of /etc/grml/grml-live.local.
Please notice that all configuration files have to be adjusted during execution
of grml-live, so please make sure you use /etc/grml/grml-live.conf as a base for
your own configuration file (usually /etc/grml/grml-live.local). Please also
notice that the configuration file specified via this option is **not** (yet)
supported inside the scripts/hooks/classes at ${GRML_FAI_CONFIG}. Instead use
/etc/grml/grml-live.local for configuration stuff used inside
${GRML_FAI_CONFIG}.

  -d **DATE**::

Use specified date as build date information on the ISO instead of the default.
The default is the date when grml-live is being executed (retrieved via
executing 'date +%Y-%m-%d'). The information is stored inside the file
/GRML/grml-version on the ISO, /etc/grml_version in the squashfs file and in all
the bootsplash related files. This option is useful if you want to provide an
ISO with release information for a specific date but have to build it in
advance. Usage example: '-d 2009-10-30'

  -D **CONFIGURATION_DIRECTORY**::

The specified directory is used as configuration directory for grml-live.
By default /usr/share/grml-live/config is used as default configuration directory.
If you want to have different configuration scripts, package definitions, etc.
without messing with the global configuration under /usr/share/grml-live/config
provided by grml-live this option provides you the option to use your own
configuration directory.
This directory is what's being referred to as ${GRML_FAI_CONFIG} throughout this
documentation.

  -e **EXTRACT_ISO_NAME**::

The squashfs inside the specified ISO will be extracted and used as the chroot.
This option is useful for remastering, in combination with -A and -b or -u.

  -F::

Force execution and do not prompt for acknowledgment of configuration.

  -g **GRML_NAME**::

Set the grml flavour name. Common usage examples: grml, grml-small, grml64.
Please do NOT use blanks and any special characters like '/', ';' inside
GRML_NAME, otherwise you might notice problems while booting.

  -h::

Display short usage information and exit.

  -i **ISO_NAME**::

Specify name of ISO which will be available inside $OUTPUT_DIRECTORY/grml_isos.

  -I **CHROOT_INSTALL**::

Specify name of source directory which provides files that should become part of
the chroot/ISO. Not enabled by default. Note: the files are installed under '/'
in the chroot so you have to create the rootfs structure on your own.

  -n::

Skip creation of the ISO file. This option is useful if you want to build/update
the chroot and/or recreate the squashfs file without building an ISO file.

  -N::

Bootstrap the chroot without building bootloader, squashfs, or finalizing the
ISO. Use this option if installation of some packages fails, you want to run
custom commands or similar.
The main use of this option is to save time by skipping stages which aren't
necessary for bootstrapping the chroot and which would get executed more than
once when iterating through the initial bootstrapping.
Alternatively, use this option as a test run of grml-live. Once you are
satisfied with the state of your grml_chroot, use grml-live **-u** to build the
remaining stages and finalize the ISO.

  -o **OUTPUT_DIRECTORY**::

Main output directory of the build process.  Some directories are created
inside this target directory, being: grml_cd (where the files for creating the
ISO are located, including the compressed squashfs file), grml_chroot (the
chroot system) and grml_isos (where the resulting ISO is stored).

  -q::

Build the ISO without (re-)creating the squashfs compressed file using mksquashfs.
This option is useful if you just want to update parts outside the chroot in the ISO.
Consider combining this option with the build-only option '-b'.

  -Q::

Build the ISO without generating a netboot package.

  -r **RELEASENAME**::

Specify name of the release.

  -R::

After building the chroot, do not clean up for a release ISO. This skips applying
the class "RELEASE".

  -s **SUITE**::

Specify the Debian suite you want to use for your live-system. If unset defaults
to "testing". Supported values are: stable, testing, unstable (or their
corresponding release names like "bookworm").

  -t **arg**::

Deprecated. Will be removed in a future release of grml-live.

  -u::

Update existing chroot instead of rebuilding it from scratch..

  -U **USERNAME**::

Sets ownership of all build output files to specified username before exiting.

  -v **VERSION_NUMBER**::

Specify version number of the release.

  -V::

Deprecated. Will be removed in a future release of grml-live.

  -w **DATE**::

The wayback machine. Build the system using Debian archives from the specified
date.  Valid date formats are yyyymmddThhmmssZ or simply yyyymmdd.  To learn
which snapshots exist, i.e. which date strings are valid, simply browse the
lists on http://snapshot.debian.org/.  If there is no import at the exact time
you specified you will get the latest available timestamp which is before the
time you specified.
This option is useful especially for release and debugging builds - for example
if you know that the Debian archive was in a good state on a specific date but
you want to build it on another day in the future, where the archive might not
be as needed anymore. Please be aware that this is restricted to the plain
Debian repositories only, as referred to in /etc/apt/sources.list.d/debian.list
(so neither the Grml repositories nor any further custom ones are affected by
the wayback machine).

  -z::

Use ZLIB instead of LZMA/XZ compression in mksquashfs part of the build process.

[[usage-examples]]
Usage examples
--------------

To get a Debian-stable and Grml-based Live-CD using ./grml
as build and output directory just run:

  # grml-live

To get a 64bit Debian-testing and grml-small based Live-CD using /srv/grml-live
as build and output directory use the following command line on your amd64
system:

  # grml-live -s testing -c GRML_SMALL -o /srv/grml-live

[NOTE]

If you have enough RAM, just run "mount -t tmpfs none /media/ramdisk" to get a
tmpfs ("RAMDISK"), and use /media/ramdisk as build and output directory - this
results in a very fast build process. Note that these files will be gone when
rebooting.

[[main-features]]
Main features of grml-live
--------------------------

* create a Grml-/Debian-based Linux Live-CD with one single command

* class based concept, providing a maximum of flexibility

* supports integration of own hooks, scripts and configuration

* supports use and integration of own Software and/or Kernels via simple use of
Debian repositories

[[class-concept]]
The class concept
-----------------

grml-live uses a class based concept, like FAI, for adjusting configuration and
customizing the installation according to your needs. This gives you flexibility
and strength without losing the simplicity in the build process.

The main and base class provided by grml-live is named GRMLBASE. grml-live will
automatically add it, together with the architecture-dependent class (being
'I386' for x86_32, 'AMD64' for x86_64 and 'ARM64' for arm64).
The GRML_SMALL and GRML_FULL classes define the official ISO builds.

The following files and directories are relevant for class GRMLBASE by default:

  ${GRML_FAI_CONFIG}/scripts/GRMLBASE/
  ${GRML_FAI_CONFIG}/media-scripts/GRMLBASE/
  ${GRML_FAI_CONFIG}/debconf/GRMLBASE
  ${GRML_FAI_CONFIG}/env/GRMLBASE
  ${GRML_FAI_CONFIG}/hooks/instsoft.GRMLBASE
  ${GRML_FAI_CONFIG}/package_config/GRMLBASE

Take a look at the next section for information about the concept of those
files/directories.

If you want to use your own configuration, extend an existing configuration
and/or add additional packages to your ISO just invent a new class (or extend an
existing one). For example if you want to use your own class named "FOOBAR" on
your amd64 build, set CLASSES="GRML_SMALL,FOOBAR" in /etc/grml/grml-live.local
or invoke grml-live using the classes option:
"grml-live -c GRML_SMALL,FOOBAR ...".

More details regarding the class concept can be found in the documentation of
FAI (being available at /usr/share/doc/fai-doc/ if you install fai-doc).
In the past, grml-live directly used FAI. Nowadays, it uses an internal
implementation of the class concept.

[[X7]]
[[classes]]
Available classes
-----------------

The package selection part of the classes can be found in
${GRML_FAI_CONFIG}/package_config whereas some further classes are defined for
example in ${GRML_FAI_CONFIG}/scripts/ so specific feature sets can be
selected. The following classes are predefined:

* DEBORPHAN: purge autoremove-able and "removed-but-not-yet-purged" packages.
While deborphan itself is not available anymore, the name of the class was kept
for backwards compatibility reasons.

* FRESHCLAM: include clamav packages and execute freshclam to get a current
clamav database

* GRMLBASE: the main class responsible for getting a minimal subset of what's
defining a Grml system. Important parts of the buildprocess are specified in
this class as well, so unless you have a really good reason you should always
use this class. Please be aware that using *just* the GRMLBASE class won't be
enough, because the kernel packages (e.g. linux-image-pass:[*]) are chosen in
further GRML_pass:[*] classes (to provide maximum flexibility with kernel
selection). If you don't want to use the existing GRML_FULL or GRML_SMALL
classes, define your own CLASS file choosing the kernel package you want to use
(and don't forget to include your CLASS in the arguments of grml-live's `-c...`
command line option).

* GRML_FULL: full featured Grml, also known as the "normal", full grml as
introduced in December 2011 (~1GB ISO size).

* GRML_SMALL: minimum sized Grml version, known as grml-small (~600MB ISO
size).

* LATEX: LaTeX(-related) packages like auctex, texlive,...
(which used to be shipped by grml before the LaTeX removal)

* LATEX_CLEANUP: get rid of several very large LaTeX directories
(like some /usr/share/doc/texlive-*, /usr/share/doc/texmf,...)

* LOCALES: use full featured locales setup (see /etc/locale.gen.grml). This
avoids to get rid of /usr/share/locale - which happens by default otherwise - as
well.

* NO_ONLINE: do not run scripts during the chroot build process which require a
network connection

* RELEASE: run some specific scripts and commands to provide the workflow for an
official grml release

* REMOVE_DOCS: get rid of documentation directories (like /usr/share/doc,
/usr/share/man/, /usr/share/info,...)

* SOURCES: retrieve Debian source packages after installation. Files will be
placed in the output directory under grml_sources.

* XORG: providing important packages for use with a base grml-featured X.org
setup

* ZFS: package selection to add support for OpenZFS/zfsonlinux

[[files]]
Files
-----

To understand the class-based configuration concept, please refer to the
FAI documentation (provided by the Debian package fai-doc). Examples can
be found in /usr/share/doc/fai-doc/examples/simple/ . Furthermore
/usr/share/doc/fai-doc/fai-guide.html/ch-config.html provides documentation
regarding configuration possibilities. Note that grml-live uses its own
implementation of the class-based concept, so not all FAI features are
available.

  /usr/sbin/grml-live

Script for the main build process. Requires root permissions for execution.

  /etc/grml/grml-live.conf

Main configuration file for grml-live which should be considered as a reference
configuration file only. Please use /etc/grml/grml-live.local for local
configuration instead.

  /etc/grml/grml-live.local

All the local configuration should go to this file. This file overrides any
defaults of grml-live. Configurations via /etc/grml/grml-live.local are preferred
over the ones from /etc/grml/grml-live.conf. If you want to override settings
from /etc/grml/grml-live.local as well you have to specify them on the grml-live
commandline.

  ${GRML_FAI_CONFIG}/

The main directory for configuration of grml-live. More details below.
Each subdirectory will have files or directories per "class". You can pick
a single or multiple classes when invoking grml-live. Only the classes you
selected (plus automatic classes) will influence the build result.
Most customizations can be applied by defining a new class for your own use.

  ${GRML_FAI_CONFIG}/env/

This directory contains files specifying environment variables for each
class. The content of all (selected) files is merged.

  ${GRML_FAI_CONFIG}/debconf/

This directory provides the files for preseeding/configuration of debconf
through files.

  ${GRML_FAI_CONFIG}/hooks/

This directory provides files for customising the build process through hooks.
Hooks are user defined programs or scripts, which are called during the
installation process.

  ${GRML_FAI_CONFIG}/package_config/

Directory with lists of software packages to be installed or removed. Please
note that GRMLBASE contains a package list defining a minimum but still
reasonable package configuration.

  ${GRML_FAI_CONFIG}/scripts/

Scripts customising the chroot (the future squashfs contents) during the
build process.

  ${GRML_FAI_CONFIG}/media-scripts/

Scripts customising the ISO contents during the build process. The squashfs
will not be available when these scripts run.

  ${GRML_FAI_CONFIG}/tools/

Tools available in PATH when scripts and media-scripts are run. Later classes
overwrite tools from earlier classes, if they share names.

[[log-files]]
Available log files
-------------------

Starting with grml-live version 0.17.0 you should find log files in a directory
named 'grml_logs' in the output directory (next to grml_isos, grml_chroot,...).

grml-live versions before 0.17.0 used to log into /var/log/grml-live.log
and /var/log/fai/grml.

[[requirements]]
Requirements for the build system
---------------------------------

* any Debian based system should be sufficient (if it doesn't work it's a bug,
please send us a bug report then). Check out <<deploy-on-debian,How do I deploy
grml-live on a plain Debian installation>> for details how to set up grml-live
on a plain, original Debian system.

* enough free disk space. At least 2GB are required for a minimal grml-live
run (\~1GB for the chroot, \~400MB for the build target, \~35MB for the netboot
files and \~350MB for the resulting ISO plus some temporary files).
If you plan to build GRML_FULL you should have at least 4GB of total free disk
space.

* fast network access for retrieving the Debian packages used for creating the
chroot (check out "local mirror" to workaround this problem as far as possible)

* your output directory should not be mounted with any of the "nodev", "noexec"
or "nosuid" mount options. (/tmp typically is at least "nodev" and "nosuid" on
most systems.)

For further information see next section.

[[faq]]
FAQ
---

[[deploy-on-debian]]
How do I deploy grml-live on a plain Debian installation?
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

The easiest way to get a running grml-live setup is to just use Grml.
Of course using grml-live on a plain, original Debian installation is supported
as well. So there we go.

What we have: plain, original Debian bookworm (v12).

What we want: build a Grml ISO based on Debian/bookworm for the amd64 architecture
using grml-live.

Instructions
^^^^^^^^^^^^

  # adjust sources.list:
  cat >> /etc/apt/sources.list << EOF

  # grml stable repository:
    deb     http://deb.grml.org/ grml-stable  main
  # deb-src http://deb.grml.org/ grml-stable  main

  # grml testing/development repository:
    deb     http://deb.grml.org/ grml-testing main
  # deb-src http://deb.grml.org/ grml-testing main
  EOF

  # get keyring for apt:
  apt-get -o Acquire::AllowInsecureRepositories=true update
  apt-get --allow-unauthenticated install grml-keyring

  cp -rv /usr/share/grml-live/config /srv

  # install relevant tools
  apt-get --no-install-recommends install grml-live

  # adjust grml-live configuration for our needs:
  cat > /etc/grml/grml-live.local << EOF
  GRML_LIVE_CONFIG=/srv/config
  ## want a faster build process and don't need smaller ISOs?
  ## if so use zlib compression
  # SQUASHFS_OPTIONS="-comp gzip -b 256k"
  ## install local files into the chroot
  # CHROOT_INSTALL="/srv/config/chroot_install"
  ## adjust if necessary (defaults to ./grml/):
  ## OUTPUT="/srv/grml-live"
  # ARCH="amd64"
  CLASSES="GRML_FULL"
  EOF

That's it. Now invoking 'grml-live -V' should build the ISO.  If everything
worked as expected the last line of the shell output should look like:

  [*] Successfully finished execution of grml-live [running 687 seconds]

and the ISO can be found inside /grml-live/grml-live/grml_isos/ then.

[[grml_fai_config_variable]]
What is $GRML_FAI_CONFIG?
~~~~~~~~~~~~~~~~~~~~~~~~~

The variable '$GRML_FAI_CONFIG' is pointing to the directory /usr/share/grml-live/config
by default.
To provide you a maximum of flexibility you can set up your own configuration directory
(e.g. based on /usr/share/grml-live/config) and use
this directory running grml-live with the '-D <config_dir>' option.
Now '$GRML_FAI_CONFIG' points to the specified directory and all the
configuration files, scripts and hooks will be taken from your
'$GRML_FAI_CONFIG' directory.

[[how-to-debug]]
I've problems with the build process. How to start debugging?
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Check out the logs inside the directory 'grml_logs' next to your grml_chroot,
grml_isos,... directories.

If you need help with grml-live or would like to see new features as part of
grml-live you can get commercial support via
link:http://grml-solutions.com/[Grml Solutions].

If there were errors during the build, grml-live should have aborted when
the error happened.

[[install-local-files]]
How do I install further files into the chroot/ISO?
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Just point the configuration variable CHROOT_INSTALL to the directory which
provides the files you would like to install. Note that the files are installed
under '/' in the chroot - so you have to create the rootfs structure on your
own. Usage example:

  GRML_FAI_CONFIG=/srv/config
  echo "GRML_FAI_CONFIG=$GRML_FAI_CONFIG" >> /etc/grml/grml-live.local
  echo "CHROOT_INSTALL=\$GRML_FAI_CONFIG/chroot_install" >> /etc/grml/grml-live.local
  mkdir -p $GRML_FAI_CONFIG/chroot_install/usr/src/
  cp -rv /usr/share/grml-live/config/* $GRML_FAI_CONFIG
  wget example.org/foo.tar.gz
  mv foo.tar.gz $GRML_FAI_CONFIG/chroot_install/usr/src/
  grml-live ...

[[local-debian-mirror]]
Can I use my own (local) Debian mirror?
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Yes. Set up an according sources.list configuration as class file in
${GRML_FAI_CONFIG}/files/${CLASS}/etc/apt/sources.list.d/ and adjust the variable
BOOTSTRAP_MIRROR in /etc/grml/grml-live.conf[.local]. If you're setting up
your own class file make sure to include the class name in the class list
(grml-live -c ...).

If you want to use a local (for example NFS mount) mirror additionally then
adjust MIRROR_DIRECTORY in /etc/grml/grml-live.conf[.local] as well.

If you want to use a HTTP Proxy (like apt-cacher-ng), set APT_PROXY. Example:

  APT_PROXY="http://localhost:3142/"

[[add-additional-debian-packages]]
How do I add additional Debian package(s) to my CD/ISO?
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Just create a new class (using the package_config directory):

  # cat > $GRML_FAI_CONFIG/package_config/MIKA << EOF
  PACKAGES install

  vim
  another_name_of_a_debian_package
  and_another_one
  EOF

and specify it when invoking grml-live then:

  # grml-live -c GRML_SMALL,MIKA

[[reset-grml-live-configuration]]
I fscked up my grml-live configuration. How do I reset it to the defaults?
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

If you make changes to the grml-live configuration files, it is recommended
you copy them to a new directory, set GRML_FAI_CONFIG and modify them there.

If you modified them inside /usr/share/grml-live, you can just reinstall
grml-live:

  # apt remove grml-live
  # apt install grml-live

Note: modified files in /usr/share/grml-live will not survive upgrades of
grml-live.

[[apt-cacher]]
Set up apt-cacher-ng for use with grml-live
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Make sure /etc/grml/grml-live.local provides according APT_PROXY and
BOOTSTRAP_MIRROR:

  # cat /etc/grml/grml-live.local
  [...]
  APT_PROXY="http://localhost:3142/"
  [...]
  BOOTSTRAP_MIRROR="http://localhost:3142/deb.debian.org/debian"

Make sure apt-cacher-ng is running ('/etc/init.d/apt-cacher-ng restart').
That's it.  All downloaded files will be cached in /var/cache/apt-cacher-ng then.

[[create-a-base-tgz]]
How do I create a base tar.gz (I386.tar.gz or AMD64.tar.gz or ARM64.tar.gz)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[[basetgz]]

This is no longer supported. grml-live will call mmdebstrap for you.

[[localrepos]]
How to use your own local repository
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Let's assume you have Debian package(s) in your filesystem inside
`/home/foobar/local-packages` and want to provide them to your grml-live build.
This can be achieved either 1) through a bind mount (using the MIRROR_DIRECTORY
configuration) or 2) by serving a repository via HTTP.

Serving via bind mount / MIRROR_DIRECTORY
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Make sure to create an according sources.list configuration file, e.g. using
your own class name `CUSTOM`:

  # cat > $GRML_FAI_CONFIG/files/CUSTOM/etc/apt/sources.list.d/local-packages.list << EOF
  deb file:///home/foobar/local-packages ./
  EOF

Add the according MIRROR_DIRECTORY configuration to your grml-live configuration:

  # echo "MIRROR_DIRECTORY='/home/foobar/packages'" >> /etc/grml/grml-live.local

Make sure the local directory looks like a mirror:

  % cd /home/foobar/packages
  % dpkg-scanpackages . /dev/null | gzip > Packages.gz

Finally invoke grml-live with your class name (`CUSTOM` in this example) added
to the list of classes on the command line (see grml-live option `-c`).

Serving a repository via HTTP
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Make sure to create an according sources.list configuration file, e.g. using
your own class name `CUSTOM`:

  # cat > $GRML_FAI_CONFIG/files/CUSTOM/etc/apt/sources.list.d/local-packages.list << EOF
  deb http://127.0.0.1:8000/ ./
  EOF

Make sure the local directory is served via HTTP on the according IP address and
port. For the `http://127.0.0.1:8000/` example from above it should be enough to
just invoke:

  % cd /home/foobar/packages
  % dpkg-scanpackages . /dev/null | gzip > Packages.gz
  % python -m http.server 8000

[TIP]
Of course you can also use a real Debian repository setup using tools like
reprepro(1) and/or using a real web server, though for quick debugging sessions
python's link:https://docs.python.org/3/library/http.server.html[http.server]
in combination with dpkg-scanpackages from package
dpkg-dev is a simple and easy approach.

Finally invoke grml-live with your class name (`CUSTOM` in this example) added
to the list of classes on the command line (see grml-live option `-c`).

[[download]]
Download / install grml-live as a Debian package
------------------------------------------------

Stable Debian packages are available through the grml-repository at
link:http://deb.grml.org/pool/main/g/grml-live/[deb.grml.org] and the latest
Git commits are available as Debian packages from
link:http://jenkins.grml.org/job/grml-live-binaries/[jenkins.grml.org].
If you want to build a Debian package on your own (using for example a specific
version or the current development tree), just execute:

  git clone git://git.grml.org/grml-live
  cd grml-live
  debuild -us -uc

[[run-from-git]]
Run grml-live directly from git
-------------------------------

In case you want to run grml-live directly from the git repository checkout
(after making sure all dependencies are installed), you should set
`GRML_FAI_CONFIG` so that a) it finds its class-based configuration files and
b) does not use the config files of an possibly installed `grml-live` package.
Usage example:

    # export GRML_FAI_CONFIG=$(pwd)/config
    # ./grml-live -s sid -a amd64 -c GRML_FULL

[[source]]
Source
------

The source of grml-live is available at
link:https://github.com/grml/grml-live/[https://github.com/grml/grml-live/]

[[bugs]]
Bugs
----

Please report feedback, link:http://grml.org/bugs/[bugreports] and wishes
link:http://grml.org/contact/[to the Grml team]!

[[documentation]]
Documentation
-------------

The most recent grml-live documentation is available online at
http://grml.org/grml-live/ and for offline reading also available
in different formats:

* http://grml.org/grml-live/grml-live.epub
* http://grml.org/grml-live/grml-live.pdf

[[authors]]
Authors
-------
Michael Prokop <mika@grml.org>

/////////////////////////////////////
// vim:ai tw=80 ft=asciidoc expandtab
/////////////////////////////////////
