default l0
menu title Grml Live Linux
prompt 0
timeout 50

label l0
menu label Grml Live Linux
linux /boot/%SHORT_NAME%/vmlinuz
initrd /boot/%SHORT_NAME%/initrd.img
fdtdir /boot/%SHORT_NAME%/dtbs/
append ro no_console_suspend cryptomgr.notests \${bootargs} fbcon=font:TER16x32 console=tty1 boot=live live-media-path=/live/%GRML_NAME%/ bootid=%BOOTID%

